export default [
  {
    url: "https://api.github.com/repos/facebook/react/issues/26001",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url:
      "https://api.github.com/repos/facebook/react/issues/26001/labels{/name}",
    comments_url:
      "https://api.github.com/repos/facebook/react/issues/26001/comments",
    events_url:
      "https://api.github.com/repos/facebook/react/issues/26001/events",
    html_url: "https://github.com/facebook/react/issues/26001",
    id: 1533533694,
    node_id: "I_kwDOAJy2Ks5bZ93-",
    number: 26001,
    title: "What font is it?",
    user: {
      login: "yap241986",
      id: 65458792,
      node_id: "MDQ6VXNlcjY1NDU4Nzky",
      avatar_url: "https://avatars.githubusercontent.com/u/65458792?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/yap241986",
      html_url: "https://github.com/yap241986",
      followers_url: "https://api.github.com/users/yap241986/followers",
      following_url:
        "https://api.github.com/users/yap241986/following{/other_user}",
      gists_url: "https://api.github.com/users/yap241986/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/yap241986/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/yap241986/subscriptions",
      organizations_url: "https://api.github.com/users/yap241986/orgs",
      repos_url: "https://api.github.com/users/yap241986/repos",
      events_url: "https://api.github.com/users/yap241986/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/yap241986/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: "2023-01-14T22:34:21Z",
    updated_at: "2023-01-14T22:34:21Z",
    closed_at: null,
    author_association: "NONE",
    active_lock_reason: null,
    body: "what is the font of React Beta Docs? \r\nCan i use them on my website?",
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/26001/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/facebook/react/issues/26001/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/26000",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url:
      "https://api.github.com/repos/facebook/react/issues/26000/labels{/name}",
    comments_url:
      "https://api.github.com/repos/facebook/react/issues/26000/comments",
    events_url:
      "https://api.github.com/repos/facebook/react/issues/26000/events",
    html_url: "https://github.com/facebook/react/pull/26000",
    id: 1533393094,
    node_id: "PR_kwDOAJy2Ks5HYwqZ",
    number: 26000,
    title: "documentation script\\git\\pre-commit",
    user: {
      login: "Rishabh-14",
      id: 77384078,
      node_id: "MDQ6VXNlcjc3Mzg0MDc4",
      avatar_url: "https://avatars.githubusercontent.com/u/77384078?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/Rishabh-14",
      html_url: "https://github.com/Rishabh-14",
      followers_url: "https://api.github.com/users/Rishabh-14/followers",
      following_url:
        "https://api.github.com/users/Rishabh-14/following{/other_user}",
      gists_url: "https://api.github.com/users/Rishabh-14/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/Rishabh-14/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/Rishabh-14/subscriptions",
      organizations_url: "https://api.github.com/users/Rishabh-14/orgs",
      repos_url: "https://api.github.com/users/Rishabh-14/repos",
      events_url: "https://api.github.com/users/Rishabh-14/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/Rishabh-14/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [
      {
        id: 196858374,
        node_id: "MDU6TGFiZWwxOTY4NTgzNzQ=",
        url: "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
        name: "CLA Signed",
        color: "e7e7e7",
        default: false,
        description: null,
      },
    ],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 2,
    created_at: "2023-01-14T17:42:36Z",
    updated_at: "2023-01-14T19:35:31Z",
    closed_at: null,
    author_association: "NONE",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/facebook/react/pulls/26000",
      html_url: "https://github.com/facebook/react/pull/26000",
      diff_url: "https://github.com/facebook/react/pull/26000.diff",
      patch_url: "https://github.com/facebook/react/pull/26000.patch",
      merged_at: null,
    },
    body: "Beginner friendly documentation for scripts/git/pre-commit ",
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/26000/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/facebook/react/issues/26000/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/25999",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url:
      "https://api.github.com/repos/facebook/react/issues/25999/labels{/name}",
    comments_url:
      "https://api.github.com/repos/facebook/react/issues/25999/comments",
    events_url:
      "https://api.github.com/repos/facebook/react/issues/25999/events",
    html_url: "https://github.com/facebook/react/pull/25999",
    id: 1533248164,
    node_id: "PR_kwDOAJy2Ks5HYR6T",
    number: 25999,
    title: "Hello",
    user: {
      login: "SHREYANSH1814",
      id: 101034768,
      node_id: "U_kgDOBgWrEA",
      avatar_url: "https://avatars.githubusercontent.com/u/101034768?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/SHREYANSH1814",
      html_url: "https://github.com/SHREYANSH1814",
      followers_url: "https://api.github.com/users/SHREYANSH1814/followers",
      following_url:
        "https://api.github.com/users/SHREYANSH1814/following{/other_user}",
      gists_url: "https://api.github.com/users/SHREYANSH1814/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/SHREYANSH1814/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/SHREYANSH1814/subscriptions",
      organizations_url: "https://api.github.com/users/SHREYANSH1814/orgs",
      repos_url: "https://api.github.com/users/SHREYANSH1814/repos",
      events_url: "https://api.github.com/users/SHREYANSH1814/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/SHREYANSH1814/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 2,
    created_at: "2023-01-14T13:11:42Z",
    updated_at: "2023-01-14T15:51:30Z",
    closed_at: "2023-01-14T13:26:10Z",
    author_association: "NONE",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/facebook/react/pulls/25999",
      html_url: "https://github.com/facebook/react/pull/25999",
      diff_url: "https://github.com/facebook/react/pull/25999.diff",
      patch_url: "https://github.com/facebook/react/pull/25999.patch",
      merged_at: null,
    },
    body: "I am new\r\n\r\n<!--\r\n  Thanks for submitting a pull request!\r\n  We appreciate you spending the time to work on these changes. Please provide enough information so that others can review your pull request. The three fields below are mandatory.\r\n\r\n  Before submitting a pull request, please make sure the following is done:\r\n\r\n  1. Fork [the repository](https://github.com/facebook/react) and create your branch from `main`.\r\n  2. Run `yarn` in the repository root.\r\n  3. If you've fixed a bug or added code that should be tested, add tests!\r\n  4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.\r\n  5. Run `yarn test --prod` to test in the production environment. It supports the same options as `yarn test`.\r\n  6. If you need a debugger, run `yarn debug-test --watch TestName`, open `chrome://inspect`, and press \"Inspect\".\r\n  7. Format your code with [prettier](https://github.com/prettier/prettier) (`yarn prettier`).\r\n  8. Make sure your code lints (`yarn lint`). Tip: `yarn linc` to only check changed files.\r\n  9. Run the [Flow](https://flowtype.org/) type checks (`yarn flow`).\r\n  10. If you haven't already, complete the CLA.\r\n\r\n  Learn more about contributing: https://reactjs.org/docs/how-to-contribute.html\r\n-->\r\n\r\n## Summary\r\n\r\n<!--\r\n Explain the **motivation** for making this change. What existing problem does the pull request solve?\r\n-->\r\n\r\n## How did you test this change?\r\n\r\n<!--\r\n  Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes the user interface.\r\n  How exactly did you verify that your PR solves the issue you wanted to solve?\r\n  If you leave this empty, your PR will very likely be closed.\r\n-->\r\n",
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/25999/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/facebook/react/issues/25999/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/25998",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url:
      "https://api.github.com/repos/facebook/react/issues/25998/labels{/name}",
    comments_url:
      "https://api.github.com/repos/facebook/react/issues/25998/comments",
    events_url:
      "https://api.github.com/repos/facebook/react/issues/25998/events",
    html_url: "https://github.com/facebook/react/pull/25998",
    id: 1532911403,
    node_id: "PR_kwDOAJy2Ks5HXM1I",
    number: 25998,
    title: "Remove findDOMNode www shim",
    user: {
      login: "kassens",
      id: 11849,
      node_id: "MDQ6VXNlcjExODQ5",
      avatar_url: "https://avatars.githubusercontent.com/u/11849?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/kassens",
      html_url: "https://github.com/kassens",
      followers_url: "https://api.github.com/users/kassens/followers",
      following_url:
        "https://api.github.com/users/kassens/following{/other_user}",
      gists_url: "https://api.github.com/users/kassens/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/kassens/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/kassens/subscriptions",
      organizations_url: "https://api.github.com/users/kassens/orgs",
      repos_url: "https://api.github.com/users/kassens/repos",
      events_url: "https://api.github.com/users/kassens/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/kassens/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [
      {
        id: 196858374,
        node_id: "MDU6TGFiZWwxOTY4NTgzNzQ=",
        url: "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
        name: "CLA Signed",
        color: "e7e7e7",
        default: false,
        description: null,
      },
      {
        id: 1775958285,
        node_id: "MDU6TGFiZWwxNzc1OTU4Mjg1",
        url: "https://api.github.com/repos/facebook/react/labels/React%20Core%20Team",
        name: "React Core Team",
        color: "9149d1",
        default: false,
        description: "Opened by a member of the React Core Team",
      },
    ],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: "2023-01-13T21:04:46Z",
    updated_at: "2023-01-13T21:27:08Z",
    closed_at: "2023-01-13T21:27:03Z",
    author_association: "MEMBER",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/facebook/react/pulls/25998",
      html_url: "https://github.com/facebook/react/pull/25998",
      diff_url: "https://github.com/facebook/react/pull/25998.diff",
      patch_url: "https://github.com/facebook/react/pull/25998.patch",
      merged_at: "2023-01-13T21:27:03Z",
    },
    body: "This shim is no longer needed on www, in fact I had already deleted it there and it's currently not on www. See D42503692 which is trying to add it back as I didn't realize this file was synced from GitHub.\r\n",
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/25998/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/facebook/react/issues/25998/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/25997",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url:
      "https://api.github.com/repos/facebook/react/issues/25997/labels{/name}",
    comments_url:
      "https://api.github.com/repos/facebook/react/issues/25997/comments",
    events_url:
      "https://api.github.com/repos/facebook/react/issues/25997/events",
    html_url: "https://github.com/facebook/react/pull/25997",
    id: 1532885710,
    node_id: "PR_kwDOAJy2Ks5HXHPI",
    number: 25997,
    title: "[www] set enableTrustedTypesIntegration to false",
    user: {
      login: "kassens",
      id: 11849,
      node_id: "MDQ6VXNlcjExODQ5",
      avatar_url: "https://avatars.githubusercontent.com/u/11849?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/kassens",
      html_url: "https://github.com/kassens",
      followers_url: "https://api.github.com/users/kassens/followers",
      following_url:
        "https://api.github.com/users/kassens/following{/other_user}",
      gists_url: "https://api.github.com/users/kassens/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/kassens/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/kassens/subscriptions",
      organizations_url: "https://api.github.com/users/kassens/orgs",
      repos_url: "https://api.github.com/users/kassens/repos",
      events_url: "https://api.github.com/users/kassens/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/kassens/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [
      {
        id: 196858374,
        node_id: "MDU6TGFiZWwxOTY4NTgzNzQ=",
        url: "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
        name: "CLA Signed",
        color: "e7e7e7",
        default: false,
        description: null,
      },
      {
        id: 1775958285,
        node_id: "MDU6TGFiZWwxNzc1OTU4Mjg1",
        url: "https://api.github.com/repos/facebook/react/labels/React%20Core%20Team",
        name: "React Core Team",
        color: "9149d1",
        default: false,
        description: "Opened by a member of the React Core Team",
      },
    ],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: "2023-01-13T20:37:47Z",
    updated_at: "2023-01-13T21:02:28Z",
    closed_at: "2023-01-13T21:02:25Z",
    author_association: "MEMBER",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/facebook/react/pulls/25997",
      html_url: "https://github.com/facebook/react/pull/25997",
      diff_url: "https://github.com/facebook/react/pull/25997.diff",
      patch_url: "https://github.com/facebook/react/pull/25997.patch",
      merged_at: "2023-01-13T21:02:25Z",
    },
    body: "This isn't configured to a dynamic value on www, so hardcode here to false.",
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/25997/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/facebook/react/issues/25997/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/25994",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url:
      "https://api.github.com/repos/facebook/react/issues/25994/labels{/name}",
    comments_url:
      "https://api.github.com/repos/facebook/react/issues/25994/comments",
    events_url:
      "https://api.github.com/repos/facebook/react/issues/25994/events",
    html_url: "https://github.com/facebook/react/issues/25994",
    id: 1531437492,
    node_id: "I_kwDOAJy2Ks5bR-G0",
    number: 25994,
    title: "Bug: react devtools TypeError: wakeable.then is not a function",
    user: {
      login: "huozhi",
      id: 4800338,
      node_id: "MDQ6VXNlcjQ4MDAzMzg=",
      avatar_url: "https://avatars.githubusercontent.com/u/4800338?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/huozhi",
      html_url: "https://github.com/huozhi",
      followers_url: "https://api.github.com/users/huozhi/followers",
      following_url:
        "https://api.github.com/users/huozhi/following{/other_user}",
      gists_url: "https://api.github.com/users/huozhi/gists{/gist_id}",
      starred_url: "https://api.github.com/users/huozhi/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/huozhi/subscriptions",
      organizations_url: "https://api.github.com/users/huozhi/orgs",
      repos_url: "https://api.github.com/users/huozhi/repos",
      events_url: "https://api.github.com/users/huozhi/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/huozhi/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [
      {
        id: 155984160,
        node_id: "MDU6TGFiZWwxNTU5ODQxNjA=",
        url: "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
        name: "Status: Unconfirmed",
        color: "d4c5f9",
        default: false,
        description: "A potential issue that we haven't yet confirmed as a bug",
      },
      {
        id: 710573595,
        node_id: "MDU6TGFiZWw3MTA1NzM1OTU=",
        url: "https://api.github.com/repos/facebook/react/labels/Component:%20Developer%20Tools",
        name: "Component: Developer Tools",
        color: "fbca04",
        default: false,
        description: null,
      },
    ],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: "2023-01-12T22:16:40Z",
    updated_at: "2023-01-13T11:39:28Z",
    closed_at: null,
    author_association: "CONTRIBUTOR",
    active_lock_reason: null,
    body: "<!--\r\n  Please provide a clear and concise description of what the bug is. Include\r\n  screenshots if needed. Please test using the latest version of the relevant\r\n  React packages to make sure your issue has not already been fixed.\r\n-->\r\n\r\nReact version: 18.3.0-next-555ece0cd-20230112\r\n\r\n## Steps To Reproduce\r\n\r\n1. open https://7rerbz-3000.preview.csb.app/\r\n\r\n<!--\r\n  Your bug will get fixed much faster if we can run your code and it doesn't\r\n  have dependencies other than React. Issues without reproduction steps or\r\n  code examples may be immediately closed as not actionable.\r\n-->\r\n\r\nLink to code example:\r\n\r\nhttps://codesandbox.io/p/github/huozhi/dynamic-suspense-forked/main\r\n\r\n<!--\r\n  Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a\r\n  repository on GitHub, or provide a minimal code example that reproduces the\r\n  problem. You may provide a screenshot of the application if you think it is\r\n  relevant to your bug report. Here are some tips for providing a minimal\r\n  example: https://stackoverflow.com/help/mcve.\r\n-->\r\n\r\n## The current behavior\r\n\r\nclient throw error while hydration with react devtools opening\r\n\r\n```\r\nreact-dom.development.js?ac89:14291 Uncaught TypeError: wakeable.then is not a function\r\n    at Object.markComponentSuspended (react_devtools_backend.js:5694:16)\r\n    at markComponentSuspended (react-dom.development.js?ac89:5153:1)\r\n    at handleThrow (react-dom.development.js?ac89:30749:1)\r\n    at renderRootSync (react-dom.development.js?ac89:30950:1)\r\n    at performSyncWorkOnRoot (react-dom.development.js?ac89:30465:1)\r\n    at flushSyncCallbacks (react-dom.development.js?ac89:14277:1)\r\n    at flushPassiveEffectsImpl (react-dom.development.js?ac89:31855:1)\r\n    at flushPassiveEffects (react-dom.development.js?ac89:31775:1)\r\n    at eval (react-dom.development.js?ac89:31517:1)\r\n    at workLoop (scheduler.development.js?bcd2:275:1)\r\n    at flushWork (scheduler.development.js?bcd2:244:1)\r\n    at performWorkUntilDeadline (scheduler.development.js?bcd2:551:1)\r\n    at k (preview-protocol.js:36:2929)\r\n    at Q (preview-protocol.js:36:3113)\r\n    at J (preview-protocol.js:36:3473)\r\n```\r\n\r\nThe `weakable` variable from react_devtools_backend.js at this time is an error instance with message `\"This is not a real error. It's an implementation detail of React's selective hydration feature. If this leaks into userspace, it's a bug in React. Please file an issue.\"`, then the later call of `weakable.then(() => ...)` will throw an error.\r\n\r\n## The expected behavior\r\n\r\nSuepsne boundaries should be resolved successfully without error, but works with react devtools disabled\r\n",
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/25994/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/facebook/react/issues/25994/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/25993",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url:
      "https://api.github.com/repos/facebook/react/issues/25993/labels{/name}",
    comments_url:
      "https://api.github.com/repos/facebook/react/issues/25993/comments",
    events_url:
      "https://api.github.com/repos/facebook/react/issues/25993/events",
    html_url: "https://github.com/facebook/react/issues/25993",
    id: 1531408967,
    node_id: "I_kwDOAJy2Ks5bR3JH",
    number: 25993,
    title: "Bug: React.Lazy causes parent components to rerender",
    user: {
      login: "barelyconfused",
      id: 16467568,
      node_id: "MDQ6VXNlcjE2NDY3NTY4",
      avatar_url: "https://avatars.githubusercontent.com/u/16467568?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/barelyconfused",
      html_url: "https://github.com/barelyconfused",
      followers_url: "https://api.github.com/users/barelyconfused/followers",
      following_url:
        "https://api.github.com/users/barelyconfused/following{/other_user}",
      gists_url: "https://api.github.com/users/barelyconfused/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/barelyconfused/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/barelyconfused/subscriptions",
      organizations_url: "https://api.github.com/users/barelyconfused/orgs",
      repos_url: "https://api.github.com/users/barelyconfused/repos",
      events_url:
        "https://api.github.com/users/barelyconfused/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/barelyconfused/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [
      {
        id: 155984160,
        node_id: "MDU6TGFiZWwxNTU5ODQxNjA=",
        url: "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
        name: "Status: Unconfirmed",
        color: "d4c5f9",
        default: false,
        description: "A potential issue that we haven't yet confirmed as a bug",
      },
    ],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: "2023-01-12T21:42:56Z",
    updated_at: "2023-01-12T21:42:56Z",
    closed_at: null,
    author_association: "NONE",
    active_lock_reason: null,
    body: "React version: 18\r\n\r\n## Steps To Reproduce\r\n\r\n1.Import Component using React.Lazy\r\n2.When component is loaded, parent Components all rerender, causing all child components to rerender. If there are hundres of components on screen, this will defeat the purpose of lazy loading. This does not happen when using third party library such as @loadable/component",
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/25993/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/facebook/react/issues/25993/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/25992",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url:
      "https://api.github.com/repos/facebook/react/issues/25992/labels{/name}",
    comments_url:
      "https://api.github.com/repos/facebook/react/issues/25992/comments",
    events_url:
      "https://api.github.com/repos/facebook/react/issues/25992/events",
    html_url: "https://github.com/facebook/react/pull/25992",
    id: 1530951201,
    node_id: "PR_kwDOAJy2Ks5HQkLD",
    number: 25992,
    title: "[cleanup] Remove warnAboutDeprecatedLifecycles feature flag",
    user: {
      login: "alunyov",
      id: 102968,
      node_id: "MDQ6VXNlcjEwMjk2OA==",
      avatar_url: "https://avatars.githubusercontent.com/u/102968?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/alunyov",
      html_url: "https://github.com/alunyov",
      followers_url: "https://api.github.com/users/alunyov/followers",
      following_url:
        "https://api.github.com/users/alunyov/following{/other_user}",
      gists_url: "https://api.github.com/users/alunyov/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/alunyov/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/alunyov/subscriptions",
      organizations_url: "https://api.github.com/users/alunyov/orgs",
      repos_url: "https://api.github.com/users/alunyov/repos",
      events_url: "https://api.github.com/users/alunyov/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/alunyov/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [
      {
        id: 196858374,
        node_id: "MDU6TGFiZWwxOTY4NTgzNzQ=",
        url: "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
        name: "CLA Signed",
        color: "e7e7e7",
        default: false,
        description: null,
      },
      {
        id: 1775958285,
        node_id: "MDU6TGFiZWwxNzc1OTU4Mjg1",
        url: "https://api.github.com/repos/facebook/react/labels/React%20Core%20Team",
        name: "React Core Team",
        color: "9149d1",
        default: false,
        description: "Opened by a member of the React Core Team",
      },
    ],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: "2023-01-12T15:48:23Z",
    updated_at: "2023-01-12T21:57:15Z",
    closed_at: "2023-01-12T21:57:15Z",
    author_association: "CONTRIBUTOR",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/facebook/react/pulls/25992",
      html_url: "https://github.com/facebook/react/pull/25992",
      diff_url: "https://github.com/facebook/react/pull/25992.diff",
      patch_url: "https://github.com/facebook/react/pull/25992.patch",
      merged_at: "2023-01-12T21:57:15Z",
    },
    body: "This `warnAboutDeprecatedLifecycles` is always true, and should be safe to remove.\r\n",
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/25992/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/facebook/react/issues/25992/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/25991",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url:
      "https://api.github.com/repos/facebook/react/issues/25991/labels{/name}",
    comments_url:
      "https://api.github.com/repos/facebook/react/issues/25991/comments",
    events_url:
      "https://api.github.com/repos/facebook/react/issues/25991/events",
    html_url: "https://github.com/facebook/react/pull/25991",
    id: 1530944506,
    node_id: "PR_kwDOAJy2Ks5HQivT",
    number: 25991,
    title: "Bump debug from 2.6.8 to 2.6.9 in /scripts/bench",
    user: {
      login: "dependabot[bot]",
      id: 49699333,
      node_id: "MDM6Qm90NDk2OTkzMzM=",
      avatar_url: "https://avatars.githubusercontent.com/in/29110?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dependabot%5Bbot%5D",
      html_url: "https://github.com/apps/dependabot",
      followers_url:
        "https://api.github.com/users/dependabot%5Bbot%5D/followers",
      following_url:
        "https://api.github.com/users/dependabot%5Bbot%5D/following{/other_user}",
      gists_url:
        "https://api.github.com/users/dependabot%5Bbot%5D/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dependabot%5Bbot%5D/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dependabot%5Bbot%5D/subscriptions",
      organizations_url:
        "https://api.github.com/users/dependabot%5Bbot%5D/orgs",
      repos_url: "https://api.github.com/users/dependabot%5Bbot%5D/repos",
      events_url:
        "https://api.github.com/users/dependabot%5Bbot%5D/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dependabot%5Bbot%5D/received_events",
      type: "Bot",
      site_admin: false,
    },
    labels: [
      {
        id: 196858374,
        node_id: "MDU6TGFiZWwxOTY4NTgzNzQ=",
        url: "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
        name: "CLA Signed",
        color: "e7e7e7",
        default: false,
        description: null,
      },
      {
        id: 1757816973,
        node_id: "MDU6TGFiZWwxNzU3ODE2OTcz",
        url: "https://api.github.com/repos/facebook/react/labels/dependencies",
        name: "dependencies",
        color: "0366d6",
        default: false,
        description: "Pull requests that update a dependency file",
      },
    ],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: "2023-01-12T15:43:52Z",
    updated_at: "2023-01-13T18:54:33Z",
    closed_at: "2023-01-13T18:54:11Z",
    author_association: "CONTRIBUTOR",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/facebook/react/pulls/25991",
      html_url: "https://github.com/facebook/react/pull/25991",
      diff_url: "https://github.com/facebook/react/pull/25991.diff",
      patch_url: "https://github.com/facebook/react/pull/25991.patch",
      merged_at: null,
    },
    body: 'Bumps [debug](https://github.com/debug-js/debug) from 2.6.8 to 2.6.9.\n<details>\n<summary>Release notes</summary>\n<p><em>Sourced from <a href="https://github.com/debug-js/debug/releases">debug\'s releases</a>.</em></p>\n<blockquote>\n<h2>2.6.9</h2>\n<h3>Patches</h3>\n<ul>\n<li>Remove ReDoS regexp in <code>%o</code> formatter: <a href="https://github-redirect.dependabot.com/debug-js/debug/issues/504">#504</a></li>\n</ul>\n<h3>Credits</h3>\n<p>Huge thanks to <a href="https://github.com/zhuangya"><code>@​zhuangya</code></a> for their help!</p>\n</blockquote>\n</details>\n<details>\n<summary>Changelog</summary>\n<p><em>Sourced from <a href="https://github.com/debug-js/debug/blob/2.6.9/CHANGELOG.md">debug\'s changelog</a>.</em></p>\n<blockquote>\n<h1>2.6.9 / 2017-09-22</h1>\n<ul>\n<li>remove ReDoS regexp in %o formatter (<a href="https://github-redirect.dependabot.com/debug-js/debug/issues/504">#504</a>)</li>\n</ul>\n</blockquote>\n</details>\n<details>\n<summary>Commits</summary>\n<ul>\n<li><a href="https://github.com/debug-js/debug/commit/13abeae468fea297d0dccc50bc55590809241083"><code>13abeae</code></a> Release 2.6.9</li>\n<li><a href="https://github.com/debug-js/debug/commit/f53962e944a87e6ca9bb622a2a12dffc22a9bb5a"><code>f53962e</code></a> remove ReDoS regexp in %o formatter (<a href="https://github-redirect.dependabot.com/debug-js/debug/issues/504">#504</a>)</li>\n<li>See full diff in <a href="https://github.com/debug-js/debug/compare/2.6.8...2.6.9">compare view</a></li>\n</ul>\n</details>\n<br />\n\n\n[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=debug&package-manager=npm_and_yarn&previous-version=2.6.8&new-version=2.6.9)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)\n\nDependabot will resolve any conflicts with this PR as long as you don\'t alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.\n\n[//]: # (dependabot-automerge-start)\n[//]: # (dependabot-automerge-end)\n\n---\n\n<details>\n<summary>Dependabot commands and options</summary>\n<br />\n\nYou can trigger Dependabot actions by commenting on this PR:\n- `@dependabot rebase` will rebase this PR\n- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it\n- `@dependabot merge` will merge this PR after your CI passes on it\n- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it\n- `@dependabot cancel merge` will cancel a previously requested merge and block automerging\n- `@dependabot reopen` will reopen this PR if it is closed\n- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually\n- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)\n- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)\n- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)\n- `@dependabot use these labels` will set the current labels as the default for future PRs for this repo and language\n- `@dependabot use these reviewers` will set the current reviewers as the default for future PRs for this repo and language\n- `@dependabot use these assignees` will set the current assignees as the default for future PRs for this repo and language\n- `@dependabot use this milestone` will set the current milestone as the default for future PRs for this repo and language\n\nYou can disable automated security fix PRs for this repo from the [Security Alerts page](https://github.com/facebook/react/network/alerts).\n\n</details>',
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/25991/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/facebook/react/issues/25991/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/25990",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url:
      "https://api.github.com/repos/facebook/react/issues/25990/labels{/name}",
    comments_url:
      "https://api.github.com/repos/facebook/react/issues/25990/comments",
    events_url:
      "https://api.github.com/repos/facebook/react/issues/25990/events",
    html_url: "https://github.com/facebook/react/pull/25990",
    id: 1530183025,
    node_id: "PR_kwDOAJy2Ks5HN9Ko",
    number: 25990,
    title: "Bump debug from 2.6.3 to 2.6.9 in /fixtures/art",
    user: {
      login: "dependabot[bot]",
      id: 49699333,
      node_id: "MDM6Qm90NDk2OTkzMzM=",
      avatar_url: "https://avatars.githubusercontent.com/in/29110?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dependabot%5Bbot%5D",
      html_url: "https://github.com/apps/dependabot",
      followers_url:
        "https://api.github.com/users/dependabot%5Bbot%5D/followers",
      following_url:
        "https://api.github.com/users/dependabot%5Bbot%5D/following{/other_user}",
      gists_url:
        "https://api.github.com/users/dependabot%5Bbot%5D/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dependabot%5Bbot%5D/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dependabot%5Bbot%5D/subscriptions",
      organizations_url:
        "https://api.github.com/users/dependabot%5Bbot%5D/orgs",
      repos_url: "https://api.github.com/users/dependabot%5Bbot%5D/repos",
      events_url:
        "https://api.github.com/users/dependabot%5Bbot%5D/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dependabot%5Bbot%5D/received_events",
      type: "Bot",
      site_admin: false,
    },
    labels: [
      {
        id: 196858374,
        node_id: "MDU6TGFiZWwxOTY4NTgzNzQ=",
        url: "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
        name: "CLA Signed",
        color: "e7e7e7",
        default: false,
        description: null,
      },
      {
        id: 1757816973,
        node_id: "MDU6TGFiZWwxNzU3ODE2OTcz",
        url: "https://api.github.com/repos/facebook/react/labels/dependencies",
        name: "dependencies",
        color: "0366d6",
        default: false,
        description: "Pull requests that update a dependency file",
      },
    ],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: "2023-01-12T06:32:32Z",
    updated_at: "2023-01-13T18:54:24Z",
    closed_at: "2023-01-13T18:54:10Z",
    author_association: "CONTRIBUTOR",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/facebook/react/pulls/25990",
      html_url: "https://github.com/facebook/react/pull/25990",
      diff_url: "https://github.com/facebook/react/pull/25990.diff",
      patch_url: "https://github.com/facebook/react/pull/25990.patch",
      merged_at: null,
    },
    body: 'Bumps [debug](https://github.com/debug-js/debug) from 2.6.3 to 2.6.9.\n<details>\n<summary>Release notes</summary>\n<p><em>Sourced from <a href="https://github.com/debug-js/debug/releases">debug\'s releases</a>.</em></p>\n<blockquote>\n<h2>2.6.9</h2>\n<h3>Patches</h3>\n<ul>\n<li>Remove ReDoS regexp in <code>%o</code> formatter: <a href="https://github-redirect.dependabot.com/debug-js/debug/issues/504">#504</a></li>\n</ul>\n<h3>Credits</h3>\n<p>Huge thanks to <a href="https://github.com/zhuangya"><code>@​zhuangya</code></a> for their help!</p>\n<h2>release 2.6.7</h2>\n<p>No release notes provided.</p>\n<h2>release 2.6.6</h2>\n<p>No release notes provided.</p>\n<h2>release 2.6.5</h2>\n<p>No release notes provided.</p>\n<h2>release 2.6.4</h2>\n<p>No release notes provided.</p>\n</blockquote>\n</details>\n<details>\n<summary>Changelog</summary>\n<p><em>Sourced from <a href="https://github.com/debug-js/debug/blob/2.6.9/CHANGELOG.md">debug\'s changelog</a>.</em></p>\n<blockquote>\n<h1>2.6.9 / 2017-09-22</h1>\n<ul>\n<li>remove ReDoS regexp in %o formatter (<a href="https://github-redirect.dependabot.com/debug-js/debug/issues/504">#504</a>)</li>\n</ul>\n<h1>2.6.8 / 2017-05-18</h1>\n<ul>\n<li>Fix: Check for undefined on browser globals (<a href="https://github-redirect.dependabot.com/debug-js/debug/issues/462">#462</a>, <a href="https://github.com/marbemac"><code>@​marbemac</code></a>)</li>\n</ul>\n<h1>2.6.7 / 2017-05-16</h1>\n<ul>\n<li>Fix: Update ms to 2.0.0 to fix regular expression denial of service vulnerability (<a href="https://github-redirect.dependabot.com/debug-js/debug/issues/458">#458</a>, <a href="https://github.com/hubdotcom"><code>@​hubdotcom</code></a>)</li>\n<li>Fix: Inline extend function in node implementation (<a href="https://github-redirect.dependabot.com/debug-js/debug/issues/452">#452</a>, <a href="https://github.com/dougwilson"><code>@​dougwilson</code></a>)</li>\n<li>Docs: Fix typo (<a href="https://github-redirect.dependabot.com/debug-js/debug/issues/455">#455</a>, <a href="https://github.com/msasad"><code>@​msasad</code></a>)</li>\n</ul>\n<h1>2.6.5 / 2017-04-27</h1>\n<ul>\n<li>Fix: null reference check on window.documentElement.style.WebkitAppearance (<a href="https://github-redirect.dependabot.com/debug-js/debug/issues/447">#447</a>, <a href="https://github.com/thebigredgeek"><code>@​thebigredgeek</code></a>)</li>\n<li>Misc: clean up browser reference checks (<a href="https://github-redirect.dependabot.com/debug-js/debug/issues/447">#447</a>, <a href="https://github.com/thebigredgeek"><code>@​thebigredgeek</code></a>)</li>\n<li>Misc: add npm-debug.log to .gitignore (<a href="https://github.com/thebigredgeek"><code>@​thebigredgeek</code></a>)</li>\n</ul>\n<h1>2.6.4 / 2017-04-20</h1>\n<ul>\n<li>Fix: bug that would occure if process.env.DEBUG is a non-string value. (<a href="https://github-redirect.dependabot.com/debug-js/debug/issues/444">#444</a>, <a href="https://github.com/LucianBuzzo"><code>@​LucianBuzzo</code></a>)</li>\n<li>Chore: ignore bower.json in npm installations. (<a href="https://github-redirect.dependabot.com/debug-js/debug/issues/437">#437</a>, <a href="https://github.com/joaovieira"><code>@​joaovieira</code></a>)</li>\n<li>Misc: update &quot;ms&quot; to v0.7.3 (<a href="https://github.com/tootallnate"><code>@​tootallnate</code></a>)</li>\n</ul>\n</blockquote>\n</details>\n<details>\n<summary>Commits</summary>\n<ul>\n<li><a href="https://github.com/debug-js/debug/commit/13abeae468fea297d0dccc50bc55590809241083"><code>13abeae</code></a> Release 2.6.9</li>\n<li><a href="https://github.com/debug-js/debug/commit/f53962e944a87e6ca9bb622a2a12dffc22a9bb5a"><code>f53962e</code></a> remove ReDoS regexp in %o formatter (<a href="https://github-redirect.dependabot.com/debug-js/debug/issues/504">#504</a>)</li>\n<li><a href="https://github.com/debug-js/debug/commit/52e1f21284322f167839e5d3a60f635c8b2dc842"><code>52e1f21</code></a> Release 2.6.8</li>\n<li><a href="https://github.com/debug-js/debug/commit/2482e08e4ef36416154ee27e9a2d60e568a01d48"><code>2482e08</code></a> Check for undefined on browser globals (<a href="https://github-redirect.dependabot.com/debug-js/debug/issues/462">#462</a>)</li>\n<li><a href="https://github.com/debug-js/debug/commit/6bb07f7e1bafa33631d8f36a779f17eb8abf5fea"><code>6bb07f7</code></a> release 2.6.7</li>\n<li><a href="https://github.com/debug-js/debug/commit/15850cb89debc3a2cd0b61ef7f9e298f257506cc"><code>15850cb</code></a> Fix Regular Expression Denial of Service (ReDoS)</li>\n<li><a href="https://github.com/debug-js/debug/commit/4a6c85c6018a4a4cff4b04f40173ca9d2c72c1da"><code>4a6c85c</code></a> update &quot;debug&quot; to v1.0.0 (<a href="https://github-redirect.dependabot.com/debug-js/debug/issues/454">#454</a>)</li>\n<li><a href="https://github.com/debug-js/debug/commit/b68dbf8cd4a8111dd4ccef56b8e2e3d463c5aadc"><code>b68dbf8</code></a> Fix typo (<a href="https://github-redirect.dependabot.com/debug-js/debug/issues/455">#455</a>)</li>\n<li><a href="https://github.com/debug-js/debug/commit/1351d2f91f20da46316be67265216761548db53c"><code>1351d2f</code></a> Inline extend function in node implementation (<a href="https://github-redirect.dependabot.com/debug-js/debug/issues/452">#452</a>)</li>\n<li><a href="https://github.com/debug-js/debug/commit/c211947ea37e1b08ee78653d78defbda7438783d"><code>c211947</code></a> update version for component</li>\n<li>Additional commits viewable in <a href="https://github.com/debug-js/debug/compare/2.6.3...2.6.9">compare view</a></li>\n</ul>\n</details>\n<br />\n\n\n[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=debug&package-manager=npm_and_yarn&previous-version=2.6.3&new-version=2.6.9)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)\n\nDependabot will resolve any conflicts with this PR as long as you don\'t alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.\n\n[//]: # (dependabot-automerge-start)\n[//]: # (dependabot-automerge-end)\n\n---\n\n<details>\n<summary>Dependabot commands and options</summary>\n<br />\n\nYou can trigger Dependabot actions by commenting on this PR:\n- `@dependabot rebase` will rebase this PR\n- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it\n- `@dependabot merge` will merge this PR after your CI passes on it\n- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it\n- `@dependabot cancel merge` will cancel a previously requested merge and block automerging\n- `@dependabot reopen` will reopen this PR if it is closed\n- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually\n- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)\n- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)\n- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)\n- `@dependabot use these labels` will set the current labels as the default for future PRs for this repo and language\n- `@dependabot use these reviewers` will set the current reviewers as the default for future PRs for this repo and language\n- `@dependabot use these assignees` will set the current assignees as the default for future PRs for this repo and language\n- `@dependabot use this milestone` will set the current milestone as the default for future PRs for this repo and language\n\nYou can disable automated security fix PRs for this repo from the [Security Alerts page](https://github.com/facebook/react/network/alerts).\n\n</details>',
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/25990/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/facebook/react/issues/25990/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/25989",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url:
      "https://api.github.com/repos/facebook/react/issues/25989/labels{/name}",
    comments_url:
      "https://api.github.com/repos/facebook/react/issues/25989/comments",
    events_url:
      "https://api.github.com/repos/facebook/react/issues/25989/events",
    html_url: "https://github.com/facebook/react/issues/25989",
    id: 1529995858,
    node_id: "I_kwDOAJy2Ks5bMeJS",
    number: 25989,
    title:
      "Feat(renderToPipeableStream): Allow passing crossorigin attribute on bootstrapScripts",
    user: {
      login: "HenriqueLimas",
      id: 2222191,
      node_id: "MDQ6VXNlcjIyMjIxOTE=",
      avatar_url: "https://avatars.githubusercontent.com/u/2222191?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/HenriqueLimas",
      html_url: "https://github.com/HenriqueLimas",
      followers_url: "https://api.github.com/users/HenriqueLimas/followers",
      following_url:
        "https://api.github.com/users/HenriqueLimas/following{/other_user}",
      gists_url: "https://api.github.com/users/HenriqueLimas/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/HenriqueLimas/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/HenriqueLimas/subscriptions",
      organizations_url: "https://api.github.com/users/HenriqueLimas/orgs",
      repos_url: "https://api.github.com/users/HenriqueLimas/repos",
      events_url: "https://api.github.com/users/HenriqueLimas/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/HenriqueLimas/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: "2023-01-12T02:24:01Z",
    updated_at: "2023-01-12T02:24:01Z",
    closed_at: null,
    author_association: "NONE",
    active_lock_reason: null,
    body: 'When using `window.onerror` in the bootstrap script that is hosted in a CDN the error message will show `"Script error."` instead of a proper error message. This is because of the [cross-origin](https://blog.sentry.io/2016/05/17/what-is-script-error/) script. To fix this issue a `crossorigin="anonymous"` attribute needs to be added in the script tag.\r\n\r\nCurrently, `bootstrapScripts` supports [`src` and `integrity`](https://github.com/facebook/react/blob/0fce6bb498357feb4465859912004b2e20fe7084/packages/react-dom-bindings/src/server/ReactDOMServerFormatConfig.js#L226) as configurations, should it also supports a `crossorigin` property?\r\n\r\n',
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/25989/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/facebook/react/issues/25989/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/25988",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url:
      "https://api.github.com/repos/facebook/react/issues/25988/labels{/name}",
    comments_url:
      "https://api.github.com/repos/facebook/react/issues/25988/comments",
    events_url:
      "https://api.github.com/repos/facebook/react/issues/25988/events",
    html_url: "https://github.com/facebook/react/pull/25988",
    id: 1529925493,
    node_id: "PR_kwDOAJy2Ks5HNFag",
    number: 25988,
    title: "test",
    user: {
      login: "muneebsoftblock",
      id: 103909001,
      node_id: "U_kgDOBjGGiQ",
      avatar_url: "https://avatars.githubusercontent.com/u/103909001?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/muneebsoftblock",
      html_url: "https://github.com/muneebsoftblock",
      followers_url: "https://api.github.com/users/muneebsoftblock/followers",
      following_url:
        "https://api.github.com/users/muneebsoftblock/following{/other_user}",
      gists_url: "https://api.github.com/users/muneebsoftblock/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/muneebsoftblock/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/muneebsoftblock/subscriptions",
      organizations_url: "https://api.github.com/users/muneebsoftblock/orgs",
      repos_url: "https://api.github.com/users/muneebsoftblock/repos",
      events_url:
        "https://api.github.com/users/muneebsoftblock/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/muneebsoftblock/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [
      {
        id: 196858374,
        node_id: "MDU6TGFiZWwxOTY4NTgzNzQ=",
        url: "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
        name: "CLA Signed",
        color: "e7e7e7",
        default: false,
        description: null,
      },
    ],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 4,
    created_at: "2023-01-12T00:55:23Z",
    updated_at: "2023-01-12T20:06:42Z",
    closed_at: "2023-01-12T20:06:41Z",
    author_association: "NONE",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/facebook/react/pulls/25988",
      html_url: "https://github.com/facebook/react/pull/25988",
      diff_url: "https://github.com/facebook/react/pull/25988.diff",
      patch_url: "https://github.com/facebook/react/pull/25988.patch",
      merged_at: null,
    },
    body: "<!--\n  Thanks for submitting a pull request!\n  We appreciate you spending the time to work on these changes. Please provide enough information so that others can review your pull request. The three fields below are mandatory.\n\n  Before submitting a pull request, please make sure the following is done:\n\n  1. Fork [the repository](https://github.com/facebook/react) and create your branch from `main`.\n  2. Run `yarn` in the repository root.\n  3. If you've fixed a bug or added code that should be tested, add tests!\n  4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.\n  5. Run `yarn test --prod` to test in the production environment. It supports the same options as `yarn test`.\n  6. If you need a debugger, run `yarn debug-test --watch TestName`, open `chrome://inspect`, and press \"Inspect\".\n  7. Format your code with [prettier](https://github.com/prettier/prettier) (`yarn prettier`).\n  8. Make sure your code lints (`yarn lint`). Tip: `yarn linc` to only check changed files.\n  9. Run the [Flow](https://flowtype.org/) type checks (`yarn flow`).\n  10. If you haven't already, complete the CLA.\n\n  Learn more about contributing: https://reactjs.org/docs/how-to-contribute.html\n-->\n\n## Summary\n\n<!--\n Explain the **motivation** for making this change. What existing problem does the pull request solve?\n-->\n\n## How did you test this change?\n\n<!--\n  Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes the user interface.\n  How exactly did you verify that your PR solves the issue you wanted to solve?\n  If you leave this empty, your PR will very likely be closed.\n-->\n",
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/25988/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/facebook/react/issues/25988/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/25987",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url:
      "https://api.github.com/repos/facebook/react/issues/25987/labels{/name}",
    comments_url:
      "https://api.github.com/repos/facebook/react/issues/25987/comments",
    events_url:
      "https://api.github.com/repos/facebook/react/issues/25987/events",
    html_url: "https://github.com/facebook/react/issues/25987",
    id: 1529749534,
    node_id: "I_kwDOAJy2Ks5bLiAe",
    number: 25987,
    title: "Bug: createPortal doesn't work",
    user: {
      login: "atillaaliyev",
      id: 6121871,
      node_id: "MDQ6VXNlcjYxMjE4NzE=",
      avatar_url: "https://avatars.githubusercontent.com/u/6121871?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/atillaaliyev",
      html_url: "https://github.com/atillaaliyev",
      followers_url: "https://api.github.com/users/atillaaliyev/followers",
      following_url:
        "https://api.github.com/users/atillaaliyev/following{/other_user}",
      gists_url: "https://api.github.com/users/atillaaliyev/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/atillaaliyev/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/atillaaliyev/subscriptions",
      organizations_url: "https://api.github.com/users/atillaaliyev/orgs",
      repos_url: "https://api.github.com/users/atillaaliyev/repos",
      events_url: "https://api.github.com/users/atillaaliyev/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/atillaaliyev/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [
      {
        id: 155984160,
        node_id: "MDU6TGFiZWwxNTU5ODQxNjA=",
        url: "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
        name: "Status: Unconfirmed",
        color: "d4c5f9",
        default: false,
        description: "A potential issue that we haven't yet confirmed as a bug",
      },
    ],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 2,
    created_at: "2023-01-11T21:51:52Z",
    updated_at: "2023-01-12T06:41:27Z",
    closed_at: null,
    author_association: "NONE",
    active_lock_reason: null,
    body: "\r\nReact version: 18.2.0\r\n\r\n## Steps To Reproduce\r\n\r\nI have two independent project : main and features project.  Features project have side effect components: CustomerSearch, UserSearch, AccountSearch, etc and i'm using in main project these.\r\n\r\nBut UserSearch component needs StoreProvider, MessageProvider, ThemeProvider or any provider in main project. And I decided using createPortal.\r\n\r\nUserSearch.tsx in features project:\r\n```\r\nexport const FibaUserSearch = <\r\n  TFieldValues extends FieldValues = Record<string, string | User>,\r\n  TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>,\r\n>(\r\n  props: UserSearchProps<TFieldValues, TName>,\r\n) => createPortal(<FibaUserSearchInner {...props} />, document.getElementById('container')) \r\n```\r\n\r\nindex.tsx in main project\r\n```\r\n return (\r\n    <>\r\n      <ThemeProvider theme={createTheme(theme, ...muiThemeLang[languageProfile])}>\r\n        <NotificationProvider>\r\n          <LayoutProvider>\r\n            <MessageProvider>\r\n              <Container id=\"container\">\r\n                <Header />\r\n                <FibaBox\r\n                  sx={{\r\n                    p: `${toolbarHeight ?? 0}px 10px 0px 10px`,\r\n                  }}\r\n                >\r\n                 <FibaUserSearch/>\r\n                </FibaBox>\r\n              </Container>\r\n            </MessageProvider>\r\n          </LayoutProvider>\r\n        </NotificationProvider>\r\n      </ThemeProvider>\r\n      <Loading />\r\n    </>\r\n  )\r\n```\r\n\r\nMy expectation is that every provider in index.tsx is available for FibaUserSearch. But createPortal doesn't work this case or I didn't understand logic clearly.\r\n\r\nThanks,",
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/25987/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/facebook/react/issues/25987/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/25986",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url:
      "https://api.github.com/repos/facebook/react/issues/25986/labels{/name}",
    comments_url:
      "https://api.github.com/repos/facebook/react/issues/25986/comments",
    events_url:
      "https://api.github.com/repos/facebook/react/issues/25986/events",
    html_url: "https://github.com/facebook/react/issues/25986",
    id: 1529371223,
    node_id: "I_kwDOAJy2Ks5bKFpX",
    number: 25986,
    title:
      '[DevTools Bug] Cannot remove node "0" because no matching node was found in the Store.',
    user: {
      login: "nellepost5",
      id: 68441532,
      node_id: "MDQ6VXNlcjY4NDQxNTMy",
      avatar_url: "https://avatars.githubusercontent.com/u/68441532?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/nellepost5",
      html_url: "https://github.com/nellepost5",
      followers_url: "https://api.github.com/users/nellepost5/followers",
      following_url:
        "https://api.github.com/users/nellepost5/following{/other_user}",
      gists_url: "https://api.github.com/users/nellepost5/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/nellepost5/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/nellepost5/subscriptions",
      organizations_url: "https://api.github.com/users/nellepost5/orgs",
      repos_url: "https://api.github.com/users/nellepost5/repos",
      events_url: "https://api.github.com/users/nellepost5/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/nellepost5/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [
      {
        id: 40929151,
        node_id: "MDU6TGFiZWw0MDkyOTE1MQ==",
        url: "https://api.github.com/repos/facebook/react/labels/Type:%20Bug",
        name: "Type: Bug",
        color: "b60205",
        default: false,
        description: null,
      },
      {
        id: 155984160,
        node_id: "MDU6TGFiZWwxNTU5ODQxNjA=",
        url: "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
        name: "Status: Unconfirmed",
        color: "d4c5f9",
        default: false,
        description: "A potential issue that we haven't yet confirmed as a bug",
      },
      {
        id: 620368407,
        node_id: "MDU6TGFiZWw2MjAzNjg0MDc=",
        url: "https://api.github.com/repos/facebook/react/labels/Resolution:%20Needs%20More%20Information",
        name: "Resolution: Needs More Information",
        color: "fffde7",
        default: false,
        description: null,
      },
      {
        id: 710573595,
        node_id: "MDU6TGFiZWw3MTA1NzM1OTU=",
        url: "https://api.github.com/repos/facebook/react/labels/Component:%20Developer%20Tools",
        name: "Component: Developer Tools",
        color: "fbca04",
        default: false,
        description: null,
      },
    ],
    state: "closed",
    locked: false,
    assignee: {
      login: "nellepost5",
      id: 68441532,
      node_id: "MDQ6VXNlcjY4NDQxNTMy",
      avatar_url: "https://avatars.githubusercontent.com/u/68441532?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/nellepost5",
      html_url: "https://github.com/nellepost5",
      followers_url: "https://api.github.com/users/nellepost5/followers",
      following_url:
        "https://api.github.com/users/nellepost5/following{/other_user}",
      gists_url: "https://api.github.com/users/nellepost5/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/nellepost5/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/nellepost5/subscriptions",
      organizations_url: "https://api.github.com/users/nellepost5/orgs",
      repos_url: "https://api.github.com/users/nellepost5/repos",
      events_url: "https://api.github.com/users/nellepost5/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/nellepost5/received_events",
      type: "User",
      site_admin: false,
    },
    assignees: [
      {
        login: "nellepost5",
        id: 68441532,
        node_id: "MDQ6VXNlcjY4NDQxNTMy",
        avatar_url: "https://avatars.githubusercontent.com/u/68441532?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/nellepost5",
        html_url: "https://github.com/nellepost5",
        followers_url: "https://api.github.com/users/nellepost5/followers",
        following_url:
          "https://api.github.com/users/nellepost5/following{/other_user}",
        gists_url: "https://api.github.com/users/nellepost5/gists{/gist_id}",
        starred_url:
          "https://api.github.com/users/nellepost5/starred{/owner}{/repo}",
        subscriptions_url:
          "https://api.github.com/users/nellepost5/subscriptions",
        organizations_url: "https://api.github.com/users/nellepost5/orgs",
        repos_url: "https://api.github.com/users/nellepost5/repos",
        events_url: "https://api.github.com/users/nellepost5/events{/privacy}",
        received_events_url:
          "https://api.github.com/users/nellepost5/received_events",
        type: "User",
        site_admin: false,
      },
    ],
    milestone: null,
    comments: 1,
    created_at: "2023-01-11T16:52:42Z",
    updated_at: "2023-01-11T16:52:58Z",
    closed_at: "2023-01-11T16:52:58Z",
    author_association: "NONE",
    active_lock_reason: null,
    body: '### Website or app\n\napp\n\n### Repro steps\n\n1.react-native run android \r\n2.react-devtools\r\n3.adb reverse tcp:8097 tcp:8097\r\n4.open dev tools on phone\r\n5.Error\n\n### How often does this bug happen?\n\nEvery time\n\n### DevTools package (automated)\n\nreact-devtools-core\n\n### DevTools version (automated)\n\n4.27.1-47f63dc54\n\n### Error message (automated)\n\nCannot remove node "0" because no matching node was found in the Store.\n\n### Error call stack (automated)\n\n```text\nat C:\\Users\\gimpl\\AppData\\Roaming\\npm\\node_modules\\react-devtools\\node_modules\\react-devtools-core\\dist\\standalone.js:48:336132\r\n    at f.emit (C:\\Users\\gimpl\\AppData\\Roaming\\npm\\node_modules\\react-devtools\\node_modules\\react-devtools-core\\dist\\standalone.js:48:281406)\r\n    at C:\\Users\\gimpl\\AppData\\Roaming\\npm\\node_modules\\react-devtools\\node_modules\\react-devtools-core\\dist\\standalone.js:48:282947\r\n    at C:\\Users\\gimpl\\AppData\\Roaming\\npm\\node_modules\\react-devtools\\node_modules\\react-devtools-core\\dist\\standalone.js:48:673319\r\n    at Array.forEach (<anonymous>)\r\n    at A.e.onmessage (C:\\Users\\gimpl\\AppData\\Roaming\\npm\\node_modules\\react-devtools\\node_modules\\react-devtools-core\\dist\\standalone.js:48:673303)\r\n    at A.t (C:\\Users\\gimpl\\AppData\\Roaming\\npm\\node_modules\\react-devtools\\node_modules\\react-devtools-core\\dist\\standalone.js:39:2836)\r\n    at A.emit (events.js:315:20)\r\n    at e.exports.L (C:\\Users\\gimpl\\AppData\\Roaming\\npm\\node_modules\\react-devtools\\node_modules\\react-devtools-core\\dist\\standalone.js:3:58894)\r\n    at e.exports.emit (events.js:315:20)\n```\n\n\n### Error component stack (automated)\n\n_No response_\n\n### GitHub query string (automated)\n\n```text\nhttps://api.github.com/search/issues?q=Cannot remove node  because no matching node was found in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react\n```\n',
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/25986/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/facebook/react/issues/25986/timeline",
    performed_via_github_app: null,
    state_reason: "completed",
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/25985",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url:
      "https://api.github.com/repos/facebook/react/issues/25985/labels{/name}",
    comments_url:
      "https://api.github.com/repos/facebook/react/issues/25985/comments",
    events_url:
      "https://api.github.com/repos/facebook/react/issues/25985/events",
    html_url: "https://github.com/facebook/react/issues/25985",
    id: 1529130160,
    node_id: "I_kwDOAJy2Ks5bJKyw",
    number: 25985,
    title:
      "Profile Section is not updated automatically after updating profile picture ",
    user: {
      login: "shreya-as",
      id: 72059672,
      node_id: "MDQ6VXNlcjcyMDU5Njcy",
      avatar_url: "https://avatars.githubusercontent.com/u/72059672?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/shreya-as",
      html_url: "https://github.com/shreya-as",
      followers_url: "https://api.github.com/users/shreya-as/followers",
      following_url:
        "https://api.github.com/users/shreya-as/following{/other_user}",
      gists_url: "https://api.github.com/users/shreya-as/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/shreya-as/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/shreya-as/subscriptions",
      organizations_url: "https://api.github.com/users/shreya-as/orgs",
      repos_url: "https://api.github.com/users/shreya-as/repos",
      events_url: "https://api.github.com/users/shreya-as/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/shreya-as/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [
      {
        id: 155984160,
        node_id: "MDU6TGFiZWwxNTU5ODQxNjA=",
        url: "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
        name: "Status: Unconfirmed",
        color: "d4c5f9",
        default: false,
        description: "A potential issue that we haven't yet confirmed as a bug",
      },
      {
        id: 155984160,
        node_id: "MDU6TGFiZWwxNTU5ODQxNjA=",
        url: "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
        name: "Status: Unconfirmed",
        color: "d4c5f9",
        default: false,
        description: "A potential issue that we haven't yet confirmed as a bug",
      },
      {
        id: 155984160,
        node_id: "MDU6TGFiZWwxNTU5ODQxNjA=",
        url: "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
        name: "Status: Unconfirmed",
        color: "d4c5f9",
        default: false,
        description: "A potential issue that we haven't yet confirmed as a bug",
      },
      {
        id: 155984160,
        node_id: "MDU6TGFiZWwxNTU5ODQxNjA=",
        url: "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
        name: "Status: Unconfirmed",
        color: "d4c5f9",
        default: false,
        description: "A potential issue that we haven't yet confirmed as a bug",
      },
      {
        id: 155984160,
        node_id: "MDU6TGFiZWwxNTU5ODQxNjA=",
        url: "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
        name: "Status: Unconfirmed",
        color: "d4c5f9",
        default: false,
        description: "A potential issue that we haven't yet confirmed as a bug",
      },
      {
        id: 155984160,
        node_id: "MDU6TGFiZWwxNTU5ODQxNjA=",
        url: "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
        name: "Status: Unconfirmed",
        color: "d4c5f9",
        default: false,
        description: "A potential issue that we haven't yet confirmed as a bug",
      },
      {
        id: 155984160,
        node_id: "MDU6TGFiZWwxNTU5ODQxNjA=",
        url: "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
        name: "Status: Unconfirmed",
        color: "d4c5f9",
        default: false,
        description: "A potential issue that we haven't yet confirmed as a bug",
      },
      {
        id: 155984160,
        node_id: "MDU6TGFiZWwxNTU5ODQxNjA=",
        url: "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
        name: "Status: Unconfirmed",
        color: "d4c5f9",
        default: false,
        description: "A potential issue that we haven't yet confirmed as a bug",
      },
      {
        id: 155984160,
        node_id: "MDU6TGFiZWwxNTU5ODQxNjA=",
        url: "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
        name: "Status: Unconfirmed",
        color: "d4c5f9",
        default: false,
        description: "A potential issue that we haven't yet confirmed as a bug",
      },
      {
        id: 155984160,
        node_id: "MDU6TGFiZWwxNTU5ODQxNjA=",
        url: "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
        name: "Status: Unconfirmed",
        color: "d4c5f9",
        default: false,
        description: "A potential issue that we haven't yet confirmed as a bug",
      },
      {
        id: 155984160,
        node_id: "MDU6TGFiZWwxNTU5ODQxNjA=",
        url: "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
        name: "Status: Unconfirmed",
        color: "d4c5f9",
        default: false,
        description: "A potential issue that we haven't yet confirmed as a bug",
      },
      {
        id: 155984160,
        node_id: "MDU6TGFiZWwxNTU5ODQxNjA=",
        url: "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
        name: "Status: Unconfirmed",
        color: "d4c5f9",
        default: false,
        description: "A potential issue that we haven't yet confirmed as a bug",
      },
      {
        id: 155984160,
        node_id: "MDU6TGFiZWwxNTU5ODQxNjA=",
        url: "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
        name: "Status: Unconfirmed",
        color: "d4c5f9",
        default: false,
        description: "A potential issue that we haven't yet confirmed as a bug",
      },
    ],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 2,
    created_at: "2023-01-11T14:14:26Z",
    updated_at: "2023-01-11T18:14:57Z",
    closed_at: null,
    author_association: "NONE",
    active_lock_reason: null,
    body: "Profile Section is not updated automatically after updating profile picture ",
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/25985/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/facebook/react/issues/25985/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
];
