export default [
  {
    url: "https://api.github.com/repos/vuejs/vue/issues/12928",
    repository_url: "https://api.github.com/repos/vuejs/vue",
    labels_url:
      "https://api.github.com/repos/vuejs/vue/issues/12928/labels{/name}",
    comments_url:
      "https://api.github.com/repos/vuejs/vue/issues/12928/comments",
    events_url: "https://api.github.com/repos/vuejs/vue/issues/12928/events",
    html_url: "https://github.com/vuejs/vue/pull/12928",
    id: 1532515533,
    node_id: "PR_kwDOALL9ps5HV2it",
    number: 12928,
    title:
      "fix(compiler): scoped slot can't udate with with different slot content",
    user: {
      login: "tinyfind",
      id: 67093787,
      node_id: "MDQ6VXNlcjY3MDkzNzg3",
      avatar_url: "https://avatars.githubusercontent.com/u/67093787?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/tinyfind",
      html_url: "https://github.com/tinyfind",
      followers_url: "https://api.github.com/users/tinyfind/followers",
      following_url:
        "https://api.github.com/users/tinyfind/following{/other_user}",
      gists_url: "https://api.github.com/users/tinyfind/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/tinyfind/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/tinyfind/subscriptions",
      organizations_url: "https://api.github.com/users/tinyfind/orgs",
      repos_url: "https://api.github.com/users/tinyfind/repos",
      events_url: "https://api.github.com/users/tinyfind/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/tinyfind/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: "2023-01-13T15:45:52Z",
    updated_at: "2023-01-14T06:30:17Z",
    closed_at: null,
    author_association: "NONE",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/vuejs/vue/pulls/12928",
      html_url: "https://github.com/vuejs/vue/pull/12928",
      diff_url: "https://github.com/vuejs/vue/pull/12928.diff",
      patch_url: "https://github.com/vuejs/vue/pull/12928.patch",
      merged_at: null,
    },
    body: "fix #12223 \r\nfix #12922\r\n\r\n**What kind of change does this PR introduce?** (check at least one)\r\n\r\n- [x] Bugfix\r\n- [ ] Feature\r\n- [ ] Code style update\r\n- [ ] Refactor\r\n- [ ] Build-related changes\r\n- [ ] Other, please describe:\r\n\r\n**Does this PR introduce a breaking change?** (check one)\r\n\r\n- [ ] Yes\r\n- [x] No\r\n\r\nIf yes, please describe the impact and migration path for existing applications:\r\n\r\n**The PR fulfills these requirements:**\r\n\r\n- [x] It's submitted to the `main` branch for v2.x (or to a previous version branch)\r\n- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where \"xxx\" is the issue number)\r\n- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup\r\n- [x] New/updated tests are included\r\n\r\nIf adding a **new feature**, the PR's description includes:\r\n- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)\r\n\r\n**Other information:**\r\n",
    reactions: {
      url: "https://api.github.com/repos/vuejs/vue/issues/12928/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/vuejs/vue/issues/12928/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/vuejs/vue/issues/12927",
    repository_url: "https://api.github.com/repos/vuejs/vue",
    labels_url:
      "https://api.github.com/repos/vuejs/vue/issues/12927/labels{/name}",
    comments_url:
      "https://api.github.com/repos/vuejs/vue/issues/12927/comments",
    events_url: "https://api.github.com/repos/vuejs/vue/issues/12927/events",
    html_url: "https://github.com/vuejs/vue/pull/12927",
    id: 1530570850,
    node_id: "PR_kwDOALL9ps5HPQ95",
    number: 12927,
    title: "chore: fix typo in utils.ts (#12927) [skip ci]",
    user: {
      login: "huxinfeng",
      id: 63422671,
      node_id: "MDQ6VXNlcjYzNDIyNjcx",
      avatar_url: "https://avatars.githubusercontent.com/u/63422671?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/huxinfeng",
      html_url: "https://github.com/huxinfeng",
      followers_url: "https://api.github.com/users/huxinfeng/followers",
      following_url:
        "https://api.github.com/users/huxinfeng/following{/other_user}",
      gists_url: "https://api.github.com/users/huxinfeng/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/huxinfeng/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/huxinfeng/subscriptions",
      organizations_url: "https://api.github.com/users/huxinfeng/orgs",
      repos_url: "https://api.github.com/users/huxinfeng/repos",
      events_url: "https://api.github.com/users/huxinfeng/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/huxinfeng/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: "2023-01-12T11:44:17Z",
    updated_at: "2023-01-12T14:47:00Z",
    closed_at: "2023-01-12T14:47:00Z",
    author_association: "CONTRIBUTOR",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/vuejs/vue/pulls/12927",
      html_url: "https://github.com/vuejs/vue/pull/12927",
      diff_url: "https://github.com/vuejs/vue/pull/12927.diff",
      patch_url: "https://github.com/vuejs/vue/pull/12927.patch",
      merged_at: "2023-01-12T14:47:00Z",
    },
    body: '<!--\r\nPlease make sure to read the Pull Request Guidelines:\r\nhttps://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#pull-request-guidelines\r\n-->\r\n\r\n<!-- PULL REQUEST TEMPLATE -->\r\n<!-- (Update "[ ]" to "[x]" to check a box) -->\r\n\r\n**What kind of change does this PR introduce?** (check at least one)\r\n\r\n- [ ] Bugfix\r\n- [ ] Feature\r\n- [ ] Code style update\r\n- [ ] Refactor\r\n- [ ] Build-related changes\r\n- [x] Other, please describe:\r\n\r\n**Does this PR introduce a breaking change?** (check one)\r\n\r\n- [ ] Yes\r\n- [x] No\r\n\r\nIf yes, please describe the impact and migration path for existing applications:\r\n\r\n**The PR fulfills these requirements:**\r\n\r\n- [ ] It\'s submitted to the `main` branch for v2.x (or to a previous version branch)\r\n- [ ] When resolving a specific issue, it\'s referenced in the PR\'s title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)\r\n- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup\r\n- [ ] New/updated tests are included\r\n\r\nIf adding a **new feature**, the PR\'s description includes:\r\n- [ ] A convincing reason for adding this feature (to avoid wasting your time, it\'s best to open a suggestion issue first and wait for approval before working on it)\r\n\r\n**Other information:**\r\n',
    reactions: {
      url: "https://api.github.com/repos/vuejs/vue/issues/12927/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/vuejs/vue/issues/12927/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/vuejs/vue/issues/12926",
    repository_url: "https://api.github.com/repos/vuejs/vue",
    labels_url:
      "https://api.github.com/repos/vuejs/vue/issues/12926/labels{/name}",
    comments_url:
      "https://api.github.com/repos/vuejs/vue/issues/12926/comments",
    events_url: "https://api.github.com/repos/vuejs/vue/issues/12926/events",
    html_url: "https://github.com/vuejs/vue/pull/12926",
    id: 1529434254,
    node_id: "PR_kwDOALL9ps5HLZQS",
    number: 12926,
    title: "Fix #12770:About the max attribute of keep-alive component",
    user: {
      login: "DaZuiZui",
      id: 66861267,
      node_id: "MDQ6VXNlcjY2ODYxMjY3",
      avatar_url: "https://avatars.githubusercontent.com/u/66861267?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/DaZuiZui",
      html_url: "https://github.com/DaZuiZui",
      followers_url: "https://api.github.com/users/DaZuiZui/followers",
      following_url:
        "https://api.github.com/users/DaZuiZui/following{/other_user}",
      gists_url: "https://api.github.com/users/DaZuiZui/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/DaZuiZui/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/DaZuiZui/subscriptions",
      organizations_url: "https://api.github.com/users/DaZuiZui/orgs",
      repos_url: "https://api.github.com/users/DaZuiZui/repos",
      events_url: "https://api.github.com/users/DaZuiZui/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/DaZuiZui/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: "2023-01-11T17:39:49Z",
    updated_at: "2023-01-11T18:45:53Z",
    closed_at: "2023-01-11T18:45:53Z",
    author_association: "NONE",
    active_lock_reason: null,
    draft: true,
    pull_request: {
      url: "https://api.github.com/repos/vuejs/vue/pulls/12926",
      html_url: "https://github.com/vuejs/vue/pull/12926",
      diff_url: "https://github.com/vuejs/vue/pull/12926.diff",
      patch_url: "https://github.com/vuejs/vue/pull/12926.patch",
      merged_at: null,
    },
    body: '<!--\r\nPlease make sure to read the Pull Request Guidelines:\r\nhttps://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#pull-request-guidelines\r\n-->\r\n\r\n<!-- PULL REQUEST TEMPLATE -->\r\n<!-- (Update "[ ]" to "[x]" to check a box) -->\r\n\r\n**What kind of change does this PR introduce?** (check at least one)\r\n\r\n- [x] Bugfix\r\n- [ ] Feature\r\n- [ ] Code style update\r\n- [ ] Refactor\r\n- [ ] Build-related changes\r\n- [ ] Other, please describe:\r\n\r\n**Does this PR introduce a breaking change?** (check one)\r\n\r\n- [ ] Yes\r\n- [x] No\r\n\r\nIf yes, please describe the impact and migration path for existing applications:\r\n\r\n**The PR fulfills these requirements:**\r\n\r\n- [] It\'s submitted to the `main` branch for v2.x (or to a previous version branch)\r\n- [] When resolving a specific issue, it\'s referenced in the PR\'s title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)\r\n- [] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup\r\n- [] New/updated tests are included\r\n\r\nIf adding a **new feature**, the PR\'s description includes:\r\n- [ ] A convincing reason for adding this feature (to avoid wasting your time, it\'s best to open a suggestion issue first and wait for approval before working on it)\r\n\r\n**Other information:**\r\n',
    reactions: {
      url: "https://api.github.com/repos/vuejs/vue/issues/12926/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/vuejs/vue/issues/12926/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/vuejs/vue/issues/12924",
    repository_url: "https://api.github.com/repos/vuejs/vue",
    labels_url:
      "https://api.github.com/repos/vuejs/vue/issues/12924/labels{/name}",
    comments_url:
      "https://api.github.com/repos/vuejs/vue/issues/12924/comments",
    events_url: "https://api.github.com/repos/vuejs/vue/issues/12924/events",
    html_url: "https://github.com/vuejs/vue/issues/12924",
    id: 1524987489,
    node_id: "I_kwDOALL9ps5a5XZh",
    number: 12924,
    title:
      "SSR with webpack5, run renderToString() report \"cannot find module ''../js/xxx.js\" when use import() to lazy load components in router configs.",
    user: {
      login: "YataoZhang",
      id: 6925257,
      node_id: "MDQ6VXNlcjY5MjUyNTc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6925257?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/YataoZhang",
      html_url: "https://github.com/YataoZhang",
      followers_url: "https://api.github.com/users/YataoZhang/followers",
      following_url:
        "https://api.github.com/users/YataoZhang/following{/other_user}",
      gists_url: "https://api.github.com/users/YataoZhang/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/YataoZhang/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/YataoZhang/subscriptions",
      organizations_url: "https://api.github.com/users/YataoZhang/orgs",
      repos_url: "https://api.github.com/users/YataoZhang/repos",
      events_url: "https://api.github.com/users/YataoZhang/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/YataoZhang/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: "2023-01-09T06:06:51Z",
    updated_at: "2023-01-09T06:06:51Z",
    closed_at: null,
    author_association: "NONE",
    active_lock_reason: null,
    body: "### Version\r\n2.7.14\r\n\r\n### Reproduction link\r\n[github.com](https://github.com/YataoZhang/vueSSRwithWebpack5)\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n### Steps to reproduce\r\nstep 1: write a simple vue-router use cases：\r\n```javascript\r\nimport Vue from 'vue';\r\nimport VueRouter from \"vue-router\";\r\n\r\nVue.use(VueRouter);\r\n\r\nexport default function () {\r\n    const router = new VueRouter({\r\n        mode: 'history',\r\n        base: '/',\r\n        routes: [\r\n            {\r\n                path: '/',\r\n                redirect: '/index'\r\n            }, {\r\n                path: '/index',\r\n                component: () => import(\r\n                    /* webpackChunkName: \"index\" */\r\n                    '@/pages/index.vue'\r\n                )\r\n            }, {\r\n                path: '/about',\r\n                component: () => import(\r\n                    /* webpackChunkName: \"about\" */\r\n                    '@/pages/about.vue'\r\n                )\r\n            }],\r\n    });\r\n    return router;\r\n}\r\n```\r\n\r\nStep 2: configuration vue.config.js for server bundle of SSR Mode:\r\n```javascript\r\nconst { defineConfig } = require('@vue/cli-service')\r\nconst nodeExternals = require('webpack-node-externals');\r\nconst VueSSRServerPlugin = require('vue-server-renderer/server-plugin');\r\n\r\nmodule.exports = defineConfig({\r\n  productionSourceMap: false,\r\n  css: {\r\n    extract: false,\r\n  },\r\n  transpileDependencies: true,\r\n  configureWebpack: {\r\n    entry: '@/enter-server.js',\r\n    target: 'node',\r\n    output: {\r\n      library: {\r\n        type: 'commonjs2'\r\n      },\r\n      libraryTarget: 'commonjs2',\r\n    },\r\n    externals: nodeExternals({\r\n      allowlist: [/\\.css$/],\r\n    }),\r\n    optimization: {\r\n      splitChunks: { chunks: 'all' },\r\n    },\r\n    plugins: [\r\n      new VueSSRServerPlugin(),\r\n    ],\r\n  }\r\n})\r\n```\r\n\r\nStep 3: write a render test case:\r\n```javascript\r\nconst { createBundleRenderer } = require('vue-server-renderer');\r\nconst serverBundle = require('./dist/vue-ssr-server-bundle.json');\r\nconst createRenderer = (bundle, options = {}) => {\r\n    return createBundleRenderer(bundle, Object.assign(options, {\r\n        runInNewContext: false\r\n    }));\r\n};\r\nlet renderer = createRenderer(serverBundle);\r\nconst ctx = {\r\n    route: { path: '/index' },\r\n};\r\nrenderer.renderToString(ctx, (err, html) => {\r\n    if (err) {\r\n        return console.log(err);\r\n    }\r\n    console.log(html);\r\n});\r\n```\r\n\r\n### What is expected?\r\nrun command: `npm run build`, and it will emit some errors:\r\n```\r\n[vue-router] Failed to resolve async component default: Error: Cannot find module '../js/index.5c9c2de1.js'\r\n```\r\n\r\n### What is actually happening?\r\nIn Webpack5, when the output.target is \"node\". it will use the `installChunk(require(\"../\" + __webpack_require__.u(chunkId)));` to load the all async modules. and \"`vue-server-renderer/server-plugin`\" will put all modules in .json file.\r\n\r\nThe reason it on the \"../\". while `renderToString()` was executed. \r\ncause cannot resolve and async components bundle with prefix ”.../“ in `evaluateModule()`.\r\n\r\n\r\n---\r\nfinally, i am apologize for my pool english.\r\n\r\n<!-- generated by vue-issues. DO NOT REMOVE -->",
    reactions: {
      url: "https://api.github.com/repos/vuejs/vue/issues/12924/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/vuejs/vue/issues/12924/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/vuejs/vue/issues/12923",
    repository_url: "https://api.github.com/repos/vuejs/vue",
    labels_url:
      "https://api.github.com/repos/vuejs/vue/issues/12923/labels{/name}",
    comments_url:
      "https://api.github.com/repos/vuejs/vue/issues/12923/comments",
    events_url: "https://api.github.com/repos/vuejs/vue/issues/12923/events",
    html_url: "https://github.com/vuejs/vue/pull/12923",
    id: 1523540590,
    node_id: "PR_kwDOALL9ps5G3qJr",
    number: 12923,
    title: "Master",
    user: {
      login: "viraj-gore",
      id: 69784041,
      node_id: "MDQ6VXNlcjY5Nzg0MDQx",
      avatar_url: "https://avatars.githubusercontent.com/u/69784041?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/viraj-gore",
      html_url: "https://github.com/viraj-gore",
      followers_url: "https://api.github.com/users/viraj-gore/followers",
      following_url:
        "https://api.github.com/users/viraj-gore/following{/other_user}",
      gists_url: "https://api.github.com/users/viraj-gore/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/viraj-gore/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/viraj-gore/subscriptions",
      organizations_url: "https://api.github.com/users/viraj-gore/orgs",
      repos_url: "https://api.github.com/users/viraj-gore/repos",
      events_url: "https://api.github.com/users/viraj-gore/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/viraj-gore/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: "2023-01-07T06:50:29Z",
    updated_at: "2023-01-07T06:50:48Z",
    closed_at: "2023-01-07T06:50:48Z",
    author_association: "NONE",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/vuejs/vue/pulls/12923",
      html_url: "https://github.com/vuejs/vue/pull/12923",
      diff_url: "https://github.com/vuejs/vue/pull/12923.diff",
      patch_url: "https://github.com/vuejs/vue/pull/12923.patch",
      merged_at: null,
    },
    body: '<!--\r\nPlease make sure to read the Pull Request Guidelines:\r\nhttps://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#pull-request-guidelines\r\n-->\r\n\r\n<!-- PULL REQUEST TEMPLATE -->\r\n<!-- (Update "[ ]" to "[x]" to check a box) -->\r\n\r\n**What kind of change does this PR introduce?** (check at least one)\r\n\r\n- [ ] Bugfix\r\n- [ ] Feature\r\n- [ ] Code style update\r\n- [ ] Refactor\r\n- [ ] Build-related changes\r\n- [ ] Other, please describe:\r\n\r\n**Does this PR introduce a breaking change?** (check one)\r\n\r\n- [ ] Yes\r\n- [ ] No\r\n\r\nIf yes, please describe the impact and migration path for existing applications:\r\n\r\n**The PR fulfills these requirements:**\r\n\r\n- [ ] It\'s submitted to the `main` branch for v2.x (or to a previous version branch)\r\n- [ ] When resolving a specific issue, it\'s referenced in the PR\'s title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)\r\n- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup\r\n- [ ] New/updated tests are included\r\n\r\nIf adding a **new feature**, the PR\'s description includes:\r\n- [ ] A convincing reason for adding this feature (to avoid wasting your time, it\'s best to open a suggestion issue first and wait for approval before working on it)\r\n\r\n**Other information:**\r\n',
    reactions: {
      url: "https://api.github.com/repos/vuejs/vue/issues/12923/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/vuejs/vue/issues/12923/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/vuejs/vue/issues/12922",
    repository_url: "https://api.github.com/repos/vuejs/vue",
    labels_url:
      "https://api.github.com/repos/vuejs/vue/issues/12922/labels{/name}",
    comments_url:
      "https://api.github.com/repos/vuejs/vue/issues/12922/comments",
    events_url: "https://api.github.com/repos/vuejs/vue/issues/12922/events",
    html_url: "https://github.com/vuejs/vue/issues/12922",
    id: 1523433022,
    node_id: "I_kwDOALL9ps5azb4-",
    number: 12922,
    title: "v-else-if scopedSlots content not update ",
    user: {
      login: "wuzhidexiaoming",
      id: 27277138,
      node_id: "MDQ6VXNlcjI3Mjc3MTM4",
      avatar_url: "https://avatars.githubusercontent.com/u/27277138?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/wuzhidexiaoming",
      html_url: "https://github.com/wuzhidexiaoming",
      followers_url: "https://api.github.com/users/wuzhidexiaoming/followers",
      following_url:
        "https://api.github.com/users/wuzhidexiaoming/following{/other_user}",
      gists_url: "https://api.github.com/users/wuzhidexiaoming/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/wuzhidexiaoming/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/wuzhidexiaoming/subscriptions",
      organizations_url: "https://api.github.com/users/wuzhidexiaoming/orgs",
      repos_url: "https://api.github.com/users/wuzhidexiaoming/repos",
      events_url:
        "https://api.github.com/users/wuzhidexiaoming/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/wuzhidexiaoming/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 2,
    created_at: "2023-01-07T03:28:02Z",
    updated_at: "2023-01-11T17:23:35Z",
    closed_at: null,
    author_association: "NONE",
    active_lock_reason: null,
    body: "### Version\r\n2.7.14\r\n\r\n### Reproduction link\r\n[codesandbox.io](https://codesandbox.io/s/elastic-wood-3duzdw?file=/src/App.vue)\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n### Steps to reproduce\r\nclick a,b,c b to c,content not update\r\n\r\n### What is expected?\r\nnormal update scopedSlot content\r\n\r\n### What is actually happening?\r\nClick a b c in turn, and found that the content of b to c has not been updated\r\n\r\n---\r\nif every div use v-if,then there will be no description problem. If for each 'Sup' component add `:value=\"value\"`, scopedSlot content will update normally\r\n\r\n<!-- generated by vue-issues. DO NOT REMOVE -->",
    reactions: {
      url: "https://api.github.com/repos/vuejs/vue/issues/12922/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/vuejs/vue/issues/12922/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/vuejs/vue/issues/12921",
    repository_url: "https://api.github.com/repos/vuejs/vue",
    labels_url:
      "https://api.github.com/repos/vuejs/vue/issues/12921/labels{/name}",
    comments_url:
      "https://api.github.com/repos/vuejs/vue/issues/12921/comments",
    events_url: "https://api.github.com/repos/vuejs/vue/issues/12921/events",
    html_url: "https://github.com/vuejs/vue/pull/12921",
    id: 1520937511,
    node_id: "PR_kwDOALL9ps5Gu0pD",
    number: 12921,
    title: "added message",
    user: {
      login: "ldavidson2",
      id: 94934268,
      node_id: "U_kgDOBaiU_A",
      avatar_url: "https://avatars.githubusercontent.com/u/94934268?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ldavidson2",
      html_url: "https://github.com/ldavidson2",
      followers_url: "https://api.github.com/users/ldavidson2/followers",
      following_url:
        "https://api.github.com/users/ldavidson2/following{/other_user}",
      gists_url: "https://api.github.com/users/ldavidson2/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/ldavidson2/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/ldavidson2/subscriptions",
      organizations_url: "https://api.github.com/users/ldavidson2/orgs",
      repos_url: "https://api.github.com/users/ldavidson2/repos",
      events_url: "https://api.github.com/users/ldavidson2/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/ldavidson2/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: "2023-01-05T15:31:29Z",
    updated_at: "2023-01-05T18:37:18Z",
    closed_at: "2023-01-05T18:37:18Z",
    author_association: "NONE",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/vuejs/vue/pulls/12921",
      html_url: "https://github.com/vuejs/vue/pull/12921",
      diff_url: "https://github.com/vuejs/vue/pull/12921.diff",
      patch_url: "https://github.com/vuejs/vue/pull/12921.patch",
      merged_at: null,
    },
    body: '<!--\r\nPlease make sure to read the Pull Request Guidelines:\r\nhttps://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#pull-request-guidelines\r\n-->\r\n\r\n<!-- PULL REQUEST TEMPLATE -->\r\n<!-- (Update "[ ]" to "[x]" to check a box) -->\r\n\r\n**What kind of change does this PR introduce?** (check at least one)\r\n\r\n- [ ] Bugfix\r\n- [ ] Feature\r\n- [ ] Code style update\r\n- [ ] Refactor\r\n- [ ] Build-related changes\r\n- [ ] Other, please describe:\r\n\r\n**Does this PR introduce a breaking change?** (check one)\r\n\r\n- [ ] Yes\r\n- [ ] No\r\n\r\nIf yes, please describe the impact and migration path for existing applications:\r\n\r\n**The PR fulfills these requirements:**\r\n\r\n- [ ] It\'s submitted to the `main` branch for v2.x (or to a previous version branch)\r\n- [ ] When resolving a specific issue, it\'s referenced in the PR\'s title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)\r\n- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup\r\n- [ ] New/updated tests are included\r\n\r\nIf adding a **new feature**, the PR\'s description includes:\r\n- [ ] A convincing reason for adding this feature (to avoid wasting your time, it\'s best to open a suggestion issue first and wait for approval before working on it)\r\n\r\n**Other information:**\r\n',
    reactions: {
      url: "https://api.github.com/repos/vuejs/vue/issues/12921/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/vuejs/vue/issues/12921/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/vuejs/vue/issues/12920",
    repository_url: "https://api.github.com/repos/vuejs/vue",
    labels_url:
      "https://api.github.com/repos/vuejs/vue/issues/12920/labels{/name}",
    comments_url:
      "https://api.github.com/repos/vuejs/vue/issues/12920/comments",
    events_url: "https://api.github.com/repos/vuejs/vue/issues/12920/events",
    html_url: "https://github.com/vuejs/vue/pull/12920",
    id: 1519176199,
    node_id: "PR_kwDOALL9ps5GovmT",
    number: 12920,
    title: "ghghgfhUpdate README.md",
    user: {
      login: "aviaman1705",
      id: 59308993,
      node_id: "MDQ6VXNlcjU5MzA4OTkz",
      avatar_url: "https://avatars.githubusercontent.com/u/59308993?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/aviaman1705",
      html_url: "https://github.com/aviaman1705",
      followers_url: "https://api.github.com/users/aviaman1705/followers",
      following_url:
        "https://api.github.com/users/aviaman1705/following{/other_user}",
      gists_url: "https://api.github.com/users/aviaman1705/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/aviaman1705/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/aviaman1705/subscriptions",
      organizations_url: "https://api.github.com/users/aviaman1705/orgs",
      repos_url: "https://api.github.com/users/aviaman1705/repos",
      events_url: "https://api.github.com/users/aviaman1705/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/aviaman1705/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: "2023-01-04T15:33:28Z",
    updated_at: "2023-01-04T15:38:16Z",
    closed_at: "2023-01-04T15:36:55Z",
    author_association: "NONE",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/vuejs/vue/pulls/12920",
      html_url: "https://github.com/vuejs/vue/pull/12920",
      diff_url: "https://github.com/vuejs/vue/pull/12920.diff",
      patch_url: "https://github.com/vuejs/vue/pull/12920.patch",
      merged_at: null,
    },
    body: '<!--\r\nPlease make sure to read the Pull Request Guidelines:\r\nhttps://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#pull-request-guidelines\r\n-->\r\n\r\n<!-- PULL REQUEST TEMPLATE -->\r\n<!-- (Update "[ ]" to "[x]" to check a box) -->\r\n\r\n**What kind of change does this PR introduce?** (check at least one)\r\n\r\n- [ ] Bugfix\r\n- [ ] Feature\r\n- [ ] Code style update\r\n- [ ] Refactor\r\n- [ ] Build-related changes\r\n- [ ] Other, please describe:\r\n\r\n**Does this PR introduce a breaking change?** (check one)\r\n\r\n- [ ] Yes\r\n- [ ] No\r\n\r\nIf yes, please describe the impact and migration path for existing applications:\r\n\r\n**The PR fulfills these requirements:**\r\n\r\n- [ ] It\'s submitted to the `main` branch for v2.x (or to a previous version branch)\r\n- [ ] When resolving a specific issue, it\'s referenced in the PR\'s title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)\r\n- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup\r\n- [ ] New/updated tests are included\r\n\r\nIf adding a **new feature**, the PR\'s description includes:\r\n- [ ] A convincing reason for adding this feature (to avoid wasting your time, it\'s best to open a suggestion issue first and wait for approval before working on it)\r\n\r\n**Other information:**\r\n',
    reactions: {
      url: "https://api.github.com/repos/vuejs/vue/issues/12920/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/vuejs/vue/issues/12920/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/vuejs/vue/issues/12919",
    repository_url: "https://api.github.com/repos/vuejs/vue",
    labels_url:
      "https://api.github.com/repos/vuejs/vue/issues/12919/labels{/name}",
    comments_url:
      "https://api.github.com/repos/vuejs/vue/issues/12919/comments",
    events_url: "https://api.github.com/repos/vuejs/vue/issues/12919/events",
    html_url: "https://github.com/vuejs/vue/pull/12919",
    id: 1518593199,
    node_id: "PR_kwDOALL9ps5Gmu4i",
    number: 12919,
    title: "Update README.md",
    user: {
      login: "margiecaina",
      id: 73752427,
      node_id: "MDQ6VXNlcjczNzUyNDI3",
      avatar_url: "https://avatars.githubusercontent.com/u/73752427?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/margiecaina",
      html_url: "https://github.com/margiecaina",
      followers_url: "https://api.github.com/users/margiecaina/followers",
      following_url:
        "https://api.github.com/users/margiecaina/following{/other_user}",
      gists_url: "https://api.github.com/users/margiecaina/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/margiecaina/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/margiecaina/subscriptions",
      organizations_url: "https://api.github.com/users/margiecaina/orgs",
      repos_url: "https://api.github.com/users/margiecaina/repos",
      events_url: "https://api.github.com/users/margiecaina/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/margiecaina/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: "2023-01-04T09:07:20Z",
    updated_at: "2023-01-04T09:17:37Z",
    closed_at: "2023-01-04T09:16:51Z",
    author_association: "NONE",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/vuejs/vue/pulls/12919",
      html_url: "https://github.com/vuejs/vue/pull/12919",
      diff_url: "https://github.com/vuejs/vue/pull/12919.diff",
      patch_url: "https://github.com/vuejs/vue/pull/12919.patch",
      merged_at: null,
    },
    body: '<!--\r\nPlease make sure to read the Pull Request Guidelines:\r\nhttps://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#pull-request-guidelines\r\n-->\r\n\r\n<!-- PULL REQUEST TEMPLATE -->\r\n<!-- (Update "[ ]" to "[x]" to check a box) -->\r\n\r\n**What kind of change does this PR introduce?** (check at least one)\r\n\r\n- [ ] Bugfix\r\n- [ ] Feature\r\n- [ ] Code style update\r\n- [ ] Refactor\r\n- [ ] Build-related changes\r\n- [ ] Other, please describe:\r\n\r\n**Does this PR introduce a breaking change?** (check one)\r\n\r\n- [ ] Yes\r\n- [ ] No\r\n\r\nIf yes, please describe the impact and migration path for existing applications:\r\n\r\n**The PR fulfills these requirements:**\r\n\r\n- [ ] It\'s submitted to the `main` branch for v2.x (or to a previous version branch)\r\n- [ ] When resolving a specific issue, it\'s referenced in the PR\'s title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)\r\n- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup\r\n- [ ] New/updated tests are included\r\n\r\nIf adding a **new feature**, the PR\'s description includes:\r\n- [ ] A convincing reason for adding this feature (to avoid wasting your time, it\'s best to open a suggestion issue first and wait for approval before working on it)\r\n\r\n**Other information:**\r\n',
    reactions: {
      url: "https://api.github.com/repos/vuejs/vue/issues/12919/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/vuejs/vue/issues/12919/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/vuejs/vue/issues/12918",
    repository_url: "https://api.github.com/repos/vuejs/vue",
    labels_url:
      "https://api.github.com/repos/vuejs/vue/issues/12918/labels{/name}",
    comments_url:
      "https://api.github.com/repos/vuejs/vue/issues/12918/comments",
    events_url: "https://api.github.com/repos/vuejs/vue/issues/12918/events",
    html_url: "https://github.com/vuejs/vue/issues/12918",
    id: 1518205400,
    node_id: "I_kwDOALL9ps5affnY",
    number: 12918,
    title: "Firefox 102.6.0 ESR addEventListener not properly works",
    user: {
      login: "ZhymabekRoman",
      id: 61125068,
      node_id: "MDQ6VXNlcjYxMTI1MDY4",
      avatar_url: "https://avatars.githubusercontent.com/u/61125068?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ZhymabekRoman",
      html_url: "https://github.com/ZhymabekRoman",
      followers_url: "https://api.github.com/users/ZhymabekRoman/followers",
      following_url:
        "https://api.github.com/users/ZhymabekRoman/following{/other_user}",
      gists_url: "https://api.github.com/users/ZhymabekRoman/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/ZhymabekRoman/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/ZhymabekRoman/subscriptions",
      organizations_url: "https://api.github.com/users/ZhymabekRoman/orgs",
      repos_url: "https://api.github.com/users/ZhymabekRoman/repos",
      events_url: "https://api.github.com/users/ZhymabekRoman/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/ZhymabekRoman/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: "2023-01-04T02:43:38Z",
    updated_at: "2023-01-09T05:35:38Z",
    closed_at: null,
    author_association: "NONE",
    active_lock_reason: null,
    body: "### Version\r\n2.7.14\r\n\r\n### Reproduction link\r\n[codepen.io](https://codepen.io/zhymabekroman/pen/MWvVByG)\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n### Steps to reproduce\r\n1) Open example: https://codepen.io/zhymabekroman/pen/MWvVByG\r\n2) Start entering number 7 in the input box\r\n\r\n### What is expected?\r\nThe input box should display the formatted phone number in the format: +7 (777) 777-77-77-77\r\nIn Chrome based browsers (tested in Edge 109.0.1518.26 beta) this works properly\r\n\r\n### What is actually happening?\r\nFirefox doesn't format numbers, just show: 777777777777777777\r\n\r\n---\r\nI don't know what the problem is exactly, maybe it's a problem with Firefox, but I still want to report the problem. Related issue (maybe): https://github.com/vuejs/vue/issues/9446. \r\n\r\nIf disable vue's events in Firefox dev tool, phone formatting being properly works:\r\n![Screenshot_20230104_083915](https://user-images.githubusercontent.com/61125068/210474765-a8474a62-148b-4eaa-9475-4c31152174af.png)\r\n\r\n\r\nAnd sorry for my English.\r\n\r\n<!-- generated by vue-issues. DO NOT REMOVE -->",
    reactions: {
      url: "https://api.github.com/repos/vuejs/vue/issues/12918/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/vuejs/vue/issues/12918/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/vuejs/vue/issues/12917",
    repository_url: "https://api.github.com/repos/vuejs/vue",
    labels_url:
      "https://api.github.com/repos/vuejs/vue/issues/12917/labels{/name}",
    comments_url:
      "https://api.github.com/repos/vuejs/vue/issues/12917/comments",
    events_url: "https://api.github.com/repos/vuejs/vue/issues/12917/events",
    html_url: "https://github.com/vuejs/vue/pull/12917",
    id: 1515994706,
    node_id: "PR_kwDOALL9ps5Gd8IS",
    number: 12917,
    title: "refactor(compiler): add stack type instead of any",
    user: {
      login: "FireBushtree",
      id: 32190667,
      node_id: "MDQ6VXNlcjMyMTkwNjY3",
      avatar_url: "https://avatars.githubusercontent.com/u/32190667?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/FireBushtree",
      html_url: "https://github.com/FireBushtree",
      followers_url: "https://api.github.com/users/FireBushtree/followers",
      following_url:
        "https://api.github.com/users/FireBushtree/following{/other_user}",
      gists_url: "https://api.github.com/users/FireBushtree/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/FireBushtree/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/FireBushtree/subscriptions",
      organizations_url: "https://api.github.com/users/FireBushtree/orgs",
      repos_url: "https://api.github.com/users/FireBushtree/repos",
      events_url: "https://api.github.com/users/FireBushtree/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/FireBushtree/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: "2023-01-02T03:36:47Z",
    updated_at: "2023-01-04T03:20:24Z",
    closed_at: null,
    author_association: "NONE",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/vuejs/vue/pulls/12917",
      html_url: "https://github.com/vuejs/vue/pull/12917",
      diff_url: "https://github.com/vuejs/vue/pull/12917.diff",
      patch_url: "https://github.com/vuejs/vue/pull/12917.patch",
      merged_at: null,
    },
    body: '<!--\r\nPlease make sure to read the Pull Request Guidelines:\r\nhttps://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#pull-request-guidelines\r\n-->\r\n\r\n<!-- PULL REQUEST TEMPLATE -->\r\n<!-- (Update "[ ]" to "[x]" to check a box) -->\r\n\r\n**What kind of change does this PR introduce?** (check at least one)\r\n\r\n- [ ] Bugfix\r\n- [ ] Feature\r\n- [ ] Code style update\r\n- [ ] Refactor\r\n- [ ] Build-related changes\r\n- [x] Other, please describe: add type description\r\n\r\n**Does this PR introduce a breaking change?** (check one)\r\n\r\n- [ ] Yes\r\n- [x] No\r\n\r\nIf yes, please describe the impact and migration path for existing applications:\r\n\r\n**The PR fulfills these requirements:**\r\n\r\n- [ ] It\'s submitted to the `main` branch for v2.x (or to a previous version branch)\r\n- [ ] When resolving a specific issue, it\'s referenced in the PR\'s title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)\r\n- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup\r\n- [ ] New/updated tests are included\r\n\r\nIf adding a **new feature**, the PR\'s description includes:\r\n- [ ] A convincing reason for adding this feature (to avoid wasting your time, it\'s best to open a suggestion issue first and wait for approval before working on it)\r\n\r\n**Other information:**\r\n',
    reactions: {
      url: "https://api.github.com/repos/vuejs/vue/issues/12917/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/vuejs/vue/issues/12917/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/vuejs/vue/issues/12916",
    repository_url: "https://api.github.com/repos/vuejs/vue",
    labels_url:
      "https://api.github.com/repos/vuejs/vue/issues/12916/labels{/name}",
    comments_url:
      "https://api.github.com/repos/vuejs/vue/issues/12916/comments",
    events_url: "https://api.github.com/repos/vuejs/vue/issues/12916/events",
    html_url: "https://github.com/vuejs/vue/pull/12916",
    id: 1515962300,
    node_id: "PR_kwDOALL9ps5Gd0_m",
    number: 12916,
    title: "Update README.md",
    user: {
      login: "zjf-cpu",
      id: 65746311,
      node_id: "MDQ6VXNlcjY1NzQ2MzEx",
      avatar_url: "https://avatars.githubusercontent.com/u/65746311?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/zjf-cpu",
      html_url: "https://github.com/zjf-cpu",
      followers_url: "https://api.github.com/users/zjf-cpu/followers",
      following_url:
        "https://api.github.com/users/zjf-cpu/following{/other_user}",
      gists_url: "https://api.github.com/users/zjf-cpu/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/zjf-cpu/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/zjf-cpu/subscriptions",
      organizations_url: "https://api.github.com/users/zjf-cpu/orgs",
      repos_url: "https://api.github.com/users/zjf-cpu/repos",
      events_url: "https://api.github.com/users/zjf-cpu/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/zjf-cpu/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: "2023-01-02T02:10:13Z",
    updated_at: "2023-01-02T02:15:38Z",
    closed_at: "2023-01-02T02:15:38Z",
    author_association: "NONE",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/vuejs/vue/pulls/12916",
      html_url: "https://github.com/vuejs/vue/pull/12916",
      diff_url: "https://github.com/vuejs/vue/pull/12916.diff",
      patch_url: "https://github.com/vuejs/vue/pull/12916.patch",
      merged_at: null,
    },
    body: '<!--\r\nPlease make sure to read the Pull Request Guidelines:\r\nhttps://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#pull-request-guidelines\r\n-->\r\n\r\n<!-- PULL REQUEST TEMPLATE -->\r\n<!-- (Update "[ ]" to "[x]" to check a box) -->\r\n\r\n**What kind of change does this PR introduce?** (check at least one)\r\n\r\n- [x] Bugfix\r\n- [ ] Feature\r\n- [ ] Code style update\r\n- [ ] Refactor\r\n- [ ] Build-related changes\r\n- [ ] Other, please describe:\r\n\r\n**Does this PR introduce a breaking change?** (check one)\r\n\r\n- [ ] Yes\r\n- [ ] No\r\n\r\nIf yes, please describe the impact and migration path for existing applications:\r\n\r\n**The PR fulfills these requirements:**\r\n\r\n- [ ] It\'s submitted to the `main` branch for v2.x (or to a previous version branch)\r\n- [ ] When resolving a specific issue, it\'s referenced in the PR\'s title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)\r\n- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup\r\n- [ ] New/updated tests are included\r\n\r\nIf adding a **new feature**, the PR\'s description includes:\r\n- [ ] A convincing reason for adding this feature (to avoid wasting your time, it\'s best to open a suggestion issue first and wait for approval before working on it)\r\n\r\n**Other information:**\r\n',
    reactions: {
      url: "https://api.github.com/repos/vuejs/vue/issues/12916/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/vuejs/vue/issues/12916/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/vuejs/vue/issues/12915",
    repository_url: "https://api.github.com/repos/vuejs/vue",
    labels_url:
      "https://api.github.com/repos/vuejs/vue/issues/12915/labels{/name}",
    comments_url:
      "https://api.github.com/repos/vuejs/vue/issues/12915/comments",
    events_url: "https://api.github.com/repos/vuejs/vue/issues/12915/events",
    html_url: "https://github.com/vuejs/vue/pull/12915",
    id: 1515050513,
    node_id: "PR_kwDOALL9ps5GatSP",
    number: 12915,
    title: "refactor: guardIESVGBug function",
    user: {
      login: "ykwy404",
      id: 64209066,
      node_id: "MDQ6VXNlcjY0MjA5MDY2",
      avatar_url: "https://avatars.githubusercontent.com/u/64209066?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ykwy404",
      html_url: "https://github.com/ykwy404",
      followers_url: "https://api.github.com/users/ykwy404/followers",
      following_url:
        "https://api.github.com/users/ykwy404/following{/other_user}",
      gists_url: "https://api.github.com/users/ykwy404/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/ykwy404/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ykwy404/subscriptions",
      organizations_url: "https://api.github.com/users/ykwy404/orgs",
      repos_url: "https://api.github.com/users/ykwy404/repos",
      events_url: "https://api.github.com/users/ykwy404/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/ykwy404/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: "2022-12-31T07:47:35Z",
    updated_at: "2022-12-31T10:17:27Z",
    closed_at: "2022-12-31T10:17:27Z",
    author_association: "NONE",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/vuejs/vue/pulls/12915",
      html_url: "https://github.com/vuejs/vue/pull/12915",
      diff_url: "https://github.com/vuejs/vue/pull/12915.diff",
      patch_url: "https://github.com/vuejs/vue/pull/12915.patch",
      merged_at: null,
    },
    body: '<!--\r\nPlease make sure to read the Pull Request Guidelines:\r\nhttps://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#pull-request-guidelines\r\n-->\r\n\r\n<!-- PULL REQUEST TEMPLATE -->\r\n<!-- (Update "[ ]" to "[x]" to check a box) -->\r\n\r\n**What kind of change does this PR introduce?** (check at least one)\r\n\r\n- [ ] Bugfix\r\n- [ ] Feature\r\n- [ ] Code style update\r\n- [x] Refactor\r\n- [ ] Build-related changes\r\n- [ ] Other, please describe:\r\n\r\n**Does this PR introduce a breaking change?** (check one)\r\n\r\n- [x] Yes\r\n- [ ] No\r\n\r\nIf yes, please describe the impact and migration path for existing applications:\r\n\r\n**The PR fulfills these requirements:**\r\n\r\n- [ ] It\'s submitted to the `main` branch for v2.x (or to a previous version branch)\r\n- [ ] When resolving a specific issue, it\'s referenced in the PR\'s title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)\r\n- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup\r\n- [ ] New/updated tests are included\r\n\r\nIf adding a **new feature**, the PR\'s description includes:\r\n- [ ] A convincing reason for adding this feature (to avoid wasting your time, it\'s best to open a suggestion issue first and wait for approval before working on it)\r\n\r\n**Other information:**\r\n',
    reactions: {
      url: "https://api.github.com/repos/vuejs/vue/issues/12915/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/vuejs/vue/issues/12915/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/vuejs/vue/issues/12914",
    repository_url: "https://api.github.com/repos/vuejs/vue",
    labels_url:
      "https://api.github.com/repos/vuejs/vue/issues/12914/labels{/name}",
    comments_url:
      "https://api.github.com/repos/vuejs/vue/issues/12914/comments",
    events_url: "https://api.github.com/repos/vuejs/vue/issues/12914/events",
    html_url: "https://github.com/vuejs/vue/issues/12914",
    id: 1513399416,
    node_id: "I_kwDOALL9ps5aNKR4",
    number: 12914,
    title: "Why not automatically convert the input number type to [number]",
    user: {
      login: "wbxl2000",
      id: 57169560,
      node_id: "MDQ6VXNlcjU3MTY5NTYw",
      avatar_url: "https://avatars.githubusercontent.com/u/57169560?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/wbxl2000",
      html_url: "https://github.com/wbxl2000",
      followers_url: "https://api.github.com/users/wbxl2000/followers",
      following_url:
        "https://api.github.com/users/wbxl2000/following{/other_user}",
      gists_url: "https://api.github.com/users/wbxl2000/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/wbxl2000/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/wbxl2000/subscriptions",
      organizations_url: "https://api.github.com/users/wbxl2000/orgs",
      repos_url: "https://api.github.com/users/wbxl2000/repos",
      events_url: "https://api.github.com/users/wbxl2000/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/wbxl2000/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: "2022-12-29T05:44:00Z",
    updated_at: "2022-12-29T12:02:55Z",
    closed_at: "2022-12-29T12:02:54Z",
    author_association: "NONE",
    active_lock_reason: null,
    body: '### What problem does this feature solve?\r\nUnder Vue 2.x, I found that I should use \'Modifiers\' when I wanna input a number and get a v-model value. But in Vue 3.x, it is automatically convert the input number type to [number] but [string] without Modifiers. So I doubt there are some reasons for it, what are they? \r\n\r\n### What does the proposed API look like?\r\n`<input type="number" v-model="count">`\r\nwhen input something, count will be type [number] always but [string]\r\n\r\n<!-- generated by vue-issues. DO NOT REMOVE -->',
    reactions: {
      url: "https://api.github.com/repos/vuejs/vue/issues/12914/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/vuejs/vue/issues/12914/timeline",
    performed_via_github_app: null,
    state_reason: "completed",
  },
  {
    url: "https://api.github.com/repos/vuejs/vue/issues/12913",
    repository_url: "https://api.github.com/repos/vuejs/vue",
    labels_url:
      "https://api.github.com/repos/vuejs/vue/issues/12913/labels{/name}",
    comments_url:
      "https://api.github.com/repos/vuejs/vue/issues/12913/comments",
    events_url: "https://api.github.com/repos/vuejs/vue/issues/12913/events",
    html_url: "https://github.com/vuejs/vue/issues/12913",
    id: 1513389303,
    node_id: "I_kwDOALL9ps5aNHz3",
    number: 12913,
    title: "A method to get the number of current history stacks",
    user: {
      login: "1593292349",
      id: 48791868,
      node_id: "MDQ6VXNlcjQ4NzkxODY4",
      avatar_url: "https://avatars.githubusercontent.com/u/48791868?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/1593292349",
      html_url: "https://github.com/1593292349",
      followers_url: "https://api.github.com/users/1593292349/followers",
      following_url:
        "https://api.github.com/users/1593292349/following{/other_user}",
      gists_url: "https://api.github.com/users/1593292349/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/1593292349/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/1593292349/subscriptions",
      organizations_url: "https://api.github.com/users/1593292349/orgs",
      repos_url: "https://api.github.com/users/1593292349/repos",
      events_url: "https://api.github.com/users/1593292349/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/1593292349/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: "2022-12-29T05:24:17Z",
    updated_at: "2022-12-29T05:25:01Z",
    closed_at: "2022-12-29T05:24:41Z",
    author_association: "NONE",
    active_lock_reason: null,
    body: "### What problem does this feature solve?\r\nImagine this scenario:\r\n\r\n1.I developed an application using hybrid development\r\n\r\n2.I'm listening to the system backbutton\r\n\r\n3.I only call router.back() when history stacks greater than 1\r\n\r\n4.When history stacks equals 1, I close the webview, or do something else like a prompt\r\n\r\n### What does the proposed API look like?\r\nstackSize():number\r\n\r\n<!-- generated by vue-issues. DO NOT REMOVE -->",
    reactions: {
      url: "https://api.github.com/repos/vuejs/vue/issues/12913/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      "https://api.github.com/repos/vuejs/vue/issues/12913/timeline",
    performed_via_github_app: null,
    state_reason: "not_planned",
  },
];
